import 'package:flutter/material.dart';

enum AppLanguage { en, tr, de, es, ar }

class AppLocalizations {
  static AppLanguage currentLanguage = AppLanguage.tr;

  static final Map<String, Map<AppLanguage, String>> _translations = {
    // ============ APP ============
    'app_name': {
      AppLanguage.en: 'DOTCAT',
      AppLanguage.tr: 'DOTCAT',
      AppLanguage.de: 'DOTCAT',
      AppLanguage.es: 'DOTCAT',
      AppLanguage.ar: 'DOTCAT',
    },
    
    // ============ NAVIGATION ============
    'home': {
      AppLanguage.en: 'Home',
      AppLanguage.tr: 'Ana Sayfa',
      AppLanguage.de: 'Startseite',
      AppLanguage.es: 'Inicio',
      AppLanguage.ar: 'الرئيسية',
    },
    'pending': {
      AppLanguage.en: 'Pending',
      AppLanguage.tr: 'Bekleyen',
      AppLanguage.de: 'Ausstehend',
      AppLanguage.es: 'Pendiente',
      AppLanguage.ar: 'قيد الانتظار',
    },
    'overdue': {
      AppLanguage.en: 'Overdue',
      AppLanguage.tr: 'Gecikmiş',
      AppLanguage.de: 'Überfällig',
      AppLanguage.es: 'Atrasado',
      AppLanguage.ar: 'متأخر',
    },
    'done': {
      AppLanguage.en: 'Done',
      AppLanguage.tr: 'Tamamlandı',
      AppLanguage.de: 'Erledigt',
      AppLanguage.es: 'Hecho',
      AppLanguage.ar: 'منتهي',
    },
    'days_left': {
      AppLanguage.en: 'days left',
      AppLanguage.tr: 'gün kaldı',
      AppLanguage.de: 'Tage übrig',
      AppLanguage.es: 'días restantes',
      AppLanguage.ar: 'أيام متبقية',
    },
    'pending_events': {
      AppLanguage.en: 'Upcoming Events',
      AppLanguage.tr: 'Bekleyen Etkinlikler',
      AppLanguage.de: 'Anstehende Termine',
      AppLanguage.es: 'Eventos Pendientes',
      AppLanguage.ar: 'الأحداث القادمة',
    },
    'no_pending': {
      AppLanguage.en: 'No pending events',
      AppLanguage.tr: 'Bekleyen etkinlik yok',
      AppLanguage.de: 'Keine anstehenden Termine',
      AppLanguage.es: 'Sin eventos pendientes',
      AppLanguage.ar: 'لا توجد أحداث معلقة',
    },
    'my_cats': {
      AppLanguage.en: 'My Cats',
      AppLanguage.tr: 'Kedilerim',
      AppLanguage.de: 'Meine Katzen',
      AppLanguage.es: 'Mis Gatos',
      AppLanguage.ar: 'قططي',
    },
    'all_cats': {
      AppLanguage.en: 'All Cats',
      AppLanguage.tr: 'Tüm Kediler',
      AppLanguage.de: 'Alle Katzen',
      AppLanguage.es: 'Todos los Gatos',
      AppLanguage.ar: 'جميع القطط',
    },
    'records': {
      AppLanguage.en: 'Records',
      AppLanguage.tr: 'Kayıtlar',
      AppLanguage.de: 'Aufzeichnungen',
      AppLanguage.es: 'Registros',
      AppLanguage.ar: 'السجلات',
    },
    'items': {
      AppLanguage.en: 'items',
      AppLanguage.tr: 'kayıt',
      AppLanguage.de: 'Einträge',
      AppLanguage.es: 'elementos',
      AppLanguage.ar: 'عناصر',
    },
    'no_records': {
      AppLanguage.en: 'No records yet',
      AppLanguage.tr: 'Henüz kayıt yok',
      AppLanguage.de: 'Noch keine Aufzeichnungen',
      AppLanguage.es: 'Sin registros aún',
      AppLanguage.ar: 'لا توجد سجلات بعد',
    },
    'latest_weight': {
      AppLanguage.en: 'Latest Weight',
      AppLanguage.tr: 'Son Ağırlık',
      AppLanguage.de: 'Letztes Gewicht',
      AppLanguage.es: 'Último Peso',
      AppLanguage.ar: 'آخر وزن',
    },
    'cats': {
      AppLanguage.en: 'Cats',
      AppLanguage.tr: 'Kedilerim',
      AppLanguage.de: 'Katzen',
      AppLanguage.es: 'Gatos',
      AppLanguage.ar: 'القطط',
    },
    'settings': {
      AppLanguage.en: 'Settings',
      AppLanguage.tr: 'Ayarlar',
      AppLanguage.de: 'Einstellungen',
      AppLanguage.es: 'Ajustes',
      AppLanguage.ar: 'الإعدادات',
    },
    
    // ============ CAT ============
    'add_cat': {
      AppLanguage.en: 'Add Cat',
      AppLanguage.tr: 'Kedi Ekle',
      AppLanguage.de: 'Katze hinzufügen',
      AppLanguage.es: 'Añadir Gato',
      AppLanguage.ar: 'إضافة قطة',
    },
    'name': {
      AppLanguage.en: 'Name',
      AppLanguage.tr: 'İsim',
      AppLanguage.de: 'Name',
      AppLanguage.es: 'Nombre',
      AppLanguage.ar: 'الاسم',
    },
    'breed': {
      AppLanguage.en: 'Breed',
      AppLanguage.tr: 'Cins',
      AppLanguage.de: 'Rasse',
      AppLanguage.es: 'Raza',
      AppLanguage.ar: 'السلالة',
    },
    'birth_date': {
      AppLanguage.en: 'Birth Date',
      AppLanguage.tr: 'Doğum Tarihi',
      AppLanguage.de: 'Geburtsdatum',
      AppLanguage.es: 'Fecha de Nacimiento',
      AppLanguage.ar: 'تاريخ الميلاد',
    },
    'weight_kg': {
      AppLanguage.en: 'Weight (kg)',
      AppLanguage.tr: 'Kilo (kg)',
      AppLanguage.de: 'Gewicht (kg)',
      AppLanguage.es: 'Peso (kg)',
      AppLanguage.ar: 'الوزن (كجم)',
    },
    'notes': {
      AppLanguage.en: 'Notes',
      AppLanguage.tr: 'Notlar',
      AppLanguage.de: 'Notizen',
      AppLanguage.es: 'Notas',
      AppLanguage.ar: 'ملاحظات',
    },
    'notes_hint': {
      AppLanguage.en: 'Add notes...',
      AppLanguage.tr: 'Not ekleyin...',
      AppLanguage.de: 'Notizen hinzufügen...',
      AppLanguage.es: 'Añadir notas...',
      AppLanguage.ar: 'إضافة ملاحظات...',
    },
    'photo': {
      AppLanguage.en: 'Photo',
      AppLanguage.tr: 'Fotoğraf',
      AppLanguage.de: 'Foto',
      AppLanguage.es: 'Foto',
      AppLanguage.ar: 'صورة',
    },
    'add_photo': {
      AppLanguage.en: 'Add Photo',
      AppLanguage.tr: 'Fotoğraf Ekle',
      AppLanguage.de: 'Foto hinzufügen',
      AppLanguage.es: 'Añadir Foto',
      AppLanguage.ar: 'إضافة صورة',
    },
    'take_photo': {
      AppLanguage.en: 'Take Photo',
      AppLanguage.tr: 'Fotoğraf Çek',
      AppLanguage.de: 'Foto aufnehmen',
      AppLanguage.es: 'Tomar Foto',
      AppLanguage.ar: 'التقاط صورة',
    },
    'choose_from_gallery': {
      AppLanguage.en: 'Choose from Gallery',
      AppLanguage.tr: 'Galeriden Seç',
      AppLanguage.de: 'Aus Galerie wählen',
      AppLanguage.es: 'Elegir de Galería',
      AppLanguage.ar: 'اختر من المعرض',
    },
    'remove_photo': {
      AppLanguage.en: 'Remove Photo',
      AppLanguage.tr: 'Fotoğrafı Kaldır',
      AppLanguage.de: 'Foto entfernen',
      AppLanguage.es: 'Eliminar Foto',
      AppLanguage.ar: 'إزالة الصورة',
    },
    'edit_cat': {
      AppLanguage.en: 'Edit Cat',
      AppLanguage.tr: 'Kediyi Düzenle',
      AppLanguage.de: 'Katze bearbeiten',
      AppLanguage.es: 'Editar Gato',
      AppLanguage.ar: 'تعديل القطة',
    },
    'delete_cat': {
      AppLanguage.en: 'Delete Cat',
      AppLanguage.tr: 'Kediyi Sil',
      AppLanguage.de: 'Katze löschen',
      AppLanguage.es: 'Eliminar Gato',
      AppLanguage.ar: 'حذف القطة',
    },
    'delete_cat_confirm': {
      AppLanguage.en: 'will be deleted',
      AppLanguage.tr: 'silinecek',
      AppLanguage.de: 'wird gelöscht',
      AppLanguage.es: 'será eliminado',
      AppLanguage.ar: 'سيتم حذفها',
    },
    'delete_cat_warning': {
      AppLanguage.en: 'All records will be deleted.',
      AppLanguage.tr: 'Tüm kayıtlar silinecek.',
      AppLanguage.de: 'Alle Aufzeichnungen werden gelöscht.',
      AppLanguage.es: 'Todos los registros serán eliminados.',
      AppLanguage.ar: 'سيتم حذف جميع السجلات.',
    },
    'cat_added': {
      AppLanguage.en: 'Cat added',
      AppLanguage.tr: 'Kedi eklendi',
      AppLanguage.de: 'Katze hinzugefügt',
      AppLanguage.es: 'Gato añadido',
      AppLanguage.ar: 'تمت إضافة القطة',
    },
    'changes_saved': {
      AppLanguage.en: 'Changes saved',
      AppLanguage.tr: 'Değişiklikler kaydedildi',
      AppLanguage.de: 'Änderungen gespeichert',
      AppLanguage.es: 'Cambios guardados',
      AppLanguage.ar: 'تم حفظ التغييرات',
    },
    'name_required': {
      AppLanguage.en: 'Name is required',
      AppLanguage.tr: 'İsim gerekli',
      AppLanguage.de: 'Name ist erforderlich',
      AppLanguage.es: 'El nombre es obligatorio',
      AppLanguage.ar: 'الاسم مطلوب',
    },
    'title_required': {
      AppLanguage.en: 'Title is required',
      AppLanguage.tr: 'Başlık gerekli',
      AppLanguage.de: 'Titel ist erforderlich',
      AppLanguage.es: 'El título es obligatorio',
      AppLanguage.ar: 'العنوان مطلوب',
    },
    'no_cats': {
      AppLanguage.en: 'No cats yet',
      AppLanguage.tr: 'Henüz kedi yok',
      AppLanguage.de: 'Noch keine Katzen',
      AppLanguage.es: 'Aún no hay gatos',
      AppLanguage.ar: 'لا توجد قطط بعد',
    },
    'add_your_first_cat': {
      AppLanguage.en: 'Add your first cat to get started',
      AppLanguage.tr: 'Başlamak için ilk kedinizi ekleyin',
      AppLanguage.de: 'Fügen Sie Ihre erste Katze hinzu',
      AppLanguage.es: 'Añade tu primer gato para empezar',
      AppLanguage.ar: 'أضف قطتك الأولى للبدء',
    },
    
    // ============ BREEDS ============
    'select_breed': {
      AppLanguage.en: 'Select Breed',
      AppLanguage.tr: 'Cins Seç',
      AppLanguage.de: 'Rasse wählen',
      AppLanguage.es: 'Seleccionar Raza',
      AppLanguage.ar: 'اختر السلالة',
    },
    'mixed_breed': {
      AppLanguage.en: 'Mixed',
      AppLanguage.tr: 'Melez',
      AppLanguage.de: 'Mischling',
      AppLanguage.es: 'Mestizo',
      AppLanguage.ar: 'مختلط',
    },
    
    // ============ RECORD TYPES ============
    'dotcat_complete': {
      AppLanguage.en: 'dotcat Complete',
      AppLanguage.tr: 'dotcat Complete',
      AppLanguage.de: 'dotcat Complete',
      AppLanguage.es: 'dotcat Complete',
      AppLanguage.ar: 'dotcat Complete',
    },
    'dotcat_complete_full': {
      AppLanguage.en: 'dotcat Complete Daily Supplement',
      AppLanguage.tr: 'dotcat Complete Günlük Takviye',
      AppLanguage.de: 'dotcat Complete Tägliche Ergänzung',
      AppLanguage.es: 'dotcat Complete Suplemento Diario',
      AppLanguage.ar: 'dotcat Complete مكمل يومي',
    },
    'vaccine': {
      AppLanguage.en: 'Vaccine',
      AppLanguage.tr: 'Aşı',
      AppLanguage.de: 'Impfung',
      AppLanguage.es: 'Vacuna',
      AppLanguage.ar: 'لقاح',
    },
    'medicine': {
      AppLanguage.en: 'Medicine',
      AppLanguage.tr: 'İlaç',
      AppLanguage.de: 'Medizin',
      AppLanguage.es: 'Medicamento',
      AppLanguage.ar: 'دواء',
    },
    'vet': {
      AppLanguage.en: 'Vet',
      AppLanguage.tr: 'Veteriner',
      AppLanguage.de: 'Tierarzt',
      AppLanguage.es: 'Veterinario',
      AppLanguage.ar: 'طبيب بيطري',
    },
    'food': {
      AppLanguage.en: 'Food',
      AppLanguage.tr: 'Mama',
      AppLanguage.de: 'Futter',
      AppLanguage.es: 'Comida',
      AppLanguage.ar: 'طعام',
    },
    'vaccine_type': {
      AppLanguage.en: 'Vaccine type',
      AppLanguage.tr: 'Aşı türü',
      AppLanguage.de: 'Impfart',
      AppLanguage.es: 'Tipo de vacuna',
      AppLanguage.ar: 'نوع اللقاح',
    },
    'medicine_type': {
      AppLanguage.en: 'Medicine type',
      AppLanguage.tr: 'İlaç türü',
      AppLanguage.de: 'Medikamentenart',
      AppLanguage.es: 'Tipo de medicamento',
      AppLanguage.ar: 'نوع الدواء',
    },
    'food_type': {
      AppLanguage.en: 'Food type',
      AppLanguage.tr: 'Mama türü',
      AppLanguage.de: 'Futterart',
      AppLanguage.es: 'Tipo de comida',
      AppLanguage.ar: 'نوع الطعام',
    },
    'visit_type': {
      AppLanguage.en: 'Visit type',
      AppLanguage.tr: 'Ziyaret türü',
      AppLanguage.de: 'Besuchsart',
      AppLanguage.es: 'Tipo de visita',
      AppLanguage.ar: 'نوع الزيارة',
    },
    
    // ============ RECORDS ============
    'add_record': {
      AppLanguage.en: 'Add Record',
      AppLanguage.tr: 'Kayıt Ekle',
      AppLanguage.de: 'Eintrag hinzufügen',
      AppLanguage.es: 'Añadir Registro',
      AppLanguage.ar: 'إضافة سجل',
    },
    'add_new_record': {
      AppLanguage.en: 'Add New Record',
      AppLanguage.tr: 'Yeni Kayıt Ekle',
      AppLanguage.de: 'Neuen Eintrag hinzufügen',
      AppLanguage.es: 'Añadir Nuevo Registro',
      AppLanguage.ar: 'إضافة سجل جديد',
    },
    'record_type': {
      AppLanguage.en: 'Type',
      AppLanguage.tr: 'Tür',
      AppLanguage.de: 'Typ',
      AppLanguage.es: 'Tipo',
      AppLanguage.ar: 'النوع',
    },
    'record_date': {
      AppLanguage.en: 'Date',
      AppLanguage.tr: 'Tarih',
      AppLanguage.de: 'Datum',
      AppLanguage.es: 'Fecha',
      AppLanguage.ar: 'التاريخ',
    },
    'record_saved': {
      AppLanguage.en: 'Record saved',
      AppLanguage.tr: 'Kayıt eklendi',
      AppLanguage.de: 'Eintrag gespeichert',
      AppLanguage.es: 'Registro guardado',
      AppLanguage.ar: 'تم حفظ السجل',
    },
    'record_detail': {
      AppLanguage.en: 'Record Detail',
      AppLanguage.tr: 'Kayıt Detayı',
      AppLanguage.de: 'Eintragsdetails',
      AppLanguage.es: 'Detalle del Registro',
      AppLanguage.ar: 'تفاصيل السجل',
    },
    'edit_record': {
      AppLanguage.en: 'Edit Record',
      AppLanguage.tr: 'Kaydı Düzenle',
      AppLanguage.de: 'Eintrag bearbeiten',
      AppLanguage.es: 'Editar Registro',
      AppLanguage.ar: 'تعديل السجل',
    },
    'record_updated': {
      AppLanguage.en: 'Record updated',
      AppLanguage.tr: 'Kayıt güncellendi',
      AppLanguage.de: 'Eintrag aktualisiert',
      AppLanguage.es: 'Registro actualizado',
      AppLanguage.ar: 'تم تحديث السجل',
    },
    'delete_record_confirm': {
      AppLanguage.en: 'Delete this record?',
      AppLanguage.tr: 'Bu kaydı sil?',
      AppLanguage.de: 'Diesen Eintrag löschen?',
      AppLanguage.es: '¿Eliminar este registro?',
      AppLanguage.ar: 'حذف هذا السجل؟',
    },
    'select_cats': {
      AppLanguage.en: 'Select Cats',
      AppLanguage.tr: 'Kedi Seç',
      AppLanguage.de: 'Katzen auswählen',
      AppLanguage.es: 'Seleccionar Gatos',
      AppLanguage.ar: 'اختر القطط',
    },
    'select_type': {
      AppLanguage.en: 'Select Type',
      AppLanguage.tr: 'Tür Seç',
      AppLanguage.de: 'Typ auswählen',
      AppLanguage.es: 'Seleccionar Tipo',
      AppLanguage.ar: 'اختر النوع',
    },
    'details': {
      AppLanguage.en: 'Details',
      AppLanguage.tr: 'Detaylar',
      AppLanguage.de: 'Details',
      AppLanguage.es: 'Detalles',
      AppLanguage.ar: 'التفاصيل',
    },
    'type': {
      AppLanguage.en: 'Type',
      AppLanguage.tr: 'Tür',
      AppLanguage.de: 'Typ',
      AppLanguage.es: 'Tipo',
      AppLanguage.ar: 'النوع',
    },
    
    // ============ FREQUENCY ============
    'frequency': {
      AppLanguage.en: 'Repeat',
      AppLanguage.tr: 'Tekrar',
      AppLanguage.de: 'Wiederholung',
      AppLanguage.es: 'Repetir',
      AppLanguage.ar: 'تكرار',
    },
    'once': {
      AppLanguage.en: 'Once',
      AppLanguage.tr: 'Bir Kez',
      AppLanguage.de: 'Einmal',
      AppLanguage.es: 'Una Vez',
      AppLanguage.ar: 'مرة واحدة',
    },
    'daily': {
      AppLanguage.en: 'Daily',
      AppLanguage.tr: 'Her Gün',
      AppLanguage.de: 'Täglich',
      AppLanguage.es: 'Diario',
      AppLanguage.ar: 'يوميًا',
    },
    'every_2_days': {
      AppLanguage.en: 'Every 2 Days',
      AppLanguage.tr: '2 Günde Bir',
      AppLanguage.de: 'Alle 2 Tage',
      AppLanguage.es: 'Cada 2 Días',
      AppLanguage.ar: 'كل يومين',
    },
    'every_3_days': {
      AppLanguage.en: 'Every 3 Days',
      AppLanguage.tr: '3 Günde Bir',
      AppLanguage.de: 'Alle 3 Tage',
      AppLanguage.es: 'Cada 3 Días',
      AppLanguage.ar: 'كل 3 أيام',
    },
    'weekly': {
      AppLanguage.en: 'Weekly',
      AppLanguage.tr: 'Haftada Bir',
      AppLanguage.de: 'Wöchentlich',
      AppLanguage.es: 'Semanal',
      AppLanguage.ar: 'أسبوعيًا',
    },
    'every_2_weeks': {
      AppLanguage.en: 'Every 2 Weeks',
      AppLanguage.tr: '2 Haftada Bir',
      AppLanguage.de: 'Alle 2 Wochen',
      AppLanguage.es: 'Cada 2 Semanas',
      AppLanguage.ar: 'كل أسبوعين',
    },
    'monthly': {
      AppLanguage.en: 'Monthly',
      AppLanguage.tr: 'Ayda Bir',
      AppLanguage.de: 'Monatlich',
      AppLanguage.es: 'Mensual',
      AppLanguage.ar: 'شهريًا',
    },
    'quarterly': {
      AppLanguage.en: 'Every 3 Months',
      AppLanguage.tr: '3 Ayda Bir',
      AppLanguage.de: 'Alle 3 Monate',
      AppLanguage.es: 'Cada 3 Meses',
      AppLanguage.ar: 'كل 3 أشهر',
    },
    'biannual': {
      AppLanguage.en: 'Every 6 Months',
      AppLanguage.tr: '6 Ayda Bir',
      AppLanguage.de: 'Alle 6 Monate',
      AppLanguage.es: 'Cada 6 Meses',
      AppLanguage.ar: 'كل 6 أشهر',
    },
    'yearly': {
      AppLanguage.en: 'Yearly',
      AppLanguage.tr: 'Yılda Bir',
      AppLanguage.de: 'Jährlich',
      AppLanguage.es: 'Anual',
      AppLanguage.ar: 'سنويًا',
    },
    'custom': {
      AppLanguage.en: 'Custom',
      AppLanguage.tr: 'Özel',
      AppLanguage.de: 'Benutzerdefiniert',
      AppLanguage.es: 'Personalizado',
      AppLanguage.ar: 'مخصص',
    },
    'every_x_days': {
      AppLanguage.en: 'Every X Days',
      AppLanguage.tr: 'Her X Günde',
      AppLanguage.de: 'Alle X Tage',
      AppLanguage.es: 'Cada X Días',
      AppLanguage.ar: 'كل X أيام',
    },
    'enter_days': {
      AppLanguage.en: 'Days',
      AppLanguage.tr: 'Gün',
      AppLanguage.de: 'Tage',
      AppLanguage.es: 'Días',
      AppLanguage.ar: 'أيام',
    },
    'next_scheduled': {
      AppLanguage.en: 'Next',
      AppLanguage.tr: 'Sonraki',
      AppLanguage.de: 'Nächster',
      AppLanguage.es: 'Siguiente',
      AppLanguage.ar: 'التالي',
    },
    
    // ============ REMINDER ============
    'reminder_settings': {
      AppLanguage.en: 'Reminder',
      AppLanguage.tr: 'Hatırlatıcı',
      AppLanguage.de: 'Erinnerung',
      AppLanguage.es: 'Recordatorio',
      AppLanguage.ar: 'تذكير',
    },
    'enable_reminder': {
      AppLanguage.en: 'Enable Reminder',
      AppLanguage.tr: 'Hatırlatıcı Aç',
      AppLanguage.de: 'Erinnerung aktivieren',
      AppLanguage.es: 'Activar Recordatorio',
      AppLanguage.ar: 'تفعيل التذكير',
    },
    'reminder_enabled': {
      AppLanguage.en: 'Reminder is on',
      AppLanguage.tr: 'Hatırlatıcı açık',
      AppLanguage.de: 'Erinnerung ist an',
      AppLanguage.es: 'Recordatorio activado',
      AppLanguage.ar: 'التذكير مفعل',
    },
    'no_reminder': {
      AppLanguage.en: 'No reminder',
      AppLanguage.tr: 'Hatırlatıcı kapalı',
      AppLanguage.de: 'Keine Erinnerung',
      AppLanguage.es: 'Sin recordatorio',
      AppLanguage.ar: 'بدون تذكير',
    },
    'on_the_day': {
      AppLanguage.en: 'On the day',
      AppLanguage.tr: 'Aynı gün',
      AppLanguage.de: 'Am selben Tag',
      AppLanguage.es: 'El mismo día',
      AppLanguage.ar: 'في نفس اليوم',
    },
    'one_day_before': {
      AppLanguage.en: '1 day before',
      AppLanguage.tr: '1 gün önce',
      AppLanguage.de: '1 Tag vorher',
      AppLanguage.es: '1 día antes',
      AppLanguage.ar: 'قبل يوم واحد',
    },
    'three_days_before': {
      AppLanguage.en: '3 days before',
      AppLanguage.tr: '3 gün önce',
      AppLanguage.de: '3 Tage vorher',
      AppLanguage.es: '3 días antes',
      AppLanguage.ar: 'قبل 3 أيام',
    },
    'one_week_before': {
      AppLanguage.en: '1 week before',
      AppLanguage.tr: '1 hafta önce',
      AppLanguage.de: '1 Woche vorher',
      AppLanguage.es: '1 semana antes',
      AppLanguage.ar: 'قبل أسبوع واحد',
    },
    'reminder_not_available': {
      AppLanguage.en: 'Not available for past dates',
      AppLanguage.tr: 'Geçmiş tarihler için kullanılamaz',
      AppLanguage.de: 'Nicht verfügbar für vergangene Daten',
      AppLanguage.es: 'No disponible para fechas pasadas',
      AppLanguage.ar: 'غير متاح للتواريخ الماضية',
    },
    
    // ============ STATUS ============
    'completed': {
      AppLanguage.en: 'Completed',
      AppLanguage.tr: 'Tamamlandı',
      AppLanguage.de: 'Abgeschlossen',
      AppLanguage.es: 'Completado',
      AppLanguage.ar: 'مكتمل',
    },
    'pending': {
      AppLanguage.en: 'Pending',
      AppLanguage.tr: 'Bekliyor',
      AppLanguage.de: 'Ausstehend',
      AppLanguage.es: 'Pendiente',
      AppLanguage.ar: 'قيد الانتظار',
    },
    'active': {
      AppLanguage.en: 'Active',
      AppLanguage.tr: 'Aktif',
      AppLanguage.de: 'Aktiv',
      AppLanguage.es: 'Activo',
      AppLanguage.ar: 'نشط',
    },
    'overdue': {
      AppLanguage.en: 'Overdue',
      AppLanguage.tr: 'Gecikmiş',
      AppLanguage.de: 'Überfällig',
      AppLanguage.es: 'Atrasado',
      AppLanguage.ar: 'متأخر',
    },
    'marked_completed': {
      AppLanguage.en: 'Marked as completed',
      AppLanguage.tr: 'Tamamlandı olarak işaretlendi',
      AppLanguage.de: 'Als abgeschlossen markiert',
      AppLanguage.es: 'Marcado como completado',
      AppLanguage.ar: 'تم وضع علامة مكتمل',
    },
    'marked_pending': {
      AppLanguage.en: 'Marked as pending',
      AppLanguage.tr: 'Bekliyor olarak işaretlendi',
      AppLanguage.de: 'Als ausstehend markiert',
      AppLanguage.es: 'Marcado como pendiente',
      AppLanguage.ar: 'تم وضع علامة قيد الانتظار',
    },
    'mark_complete': {
      AppLanguage.en: 'Mark as Complete',
      AppLanguage.tr: 'Tamamlandı İşaretle',
      AppLanguage.de: 'Als erledigt markieren',
      AppLanguage.es: 'Marcar como Completado',
      AppLanguage.ar: 'وضع علامة مكتمل',
    },
    'has_overdue': {
      AppLanguage.en: 'overdue event(s)',
      AppLanguage.tr: 'gecikmiş etkinlik',
      AppLanguage.de: 'überfällige(s) Ereignis(se)',
      AppLanguage.es: 'evento(s) atrasado(s)',
      AppLanguage.ar: 'حدث(أحداث) متأخر',
    },
    
    // ============ TIME/DATE ============
    'time': {
      AppLanguage.en: 'Time',
      AppLanguage.tr: 'Saat',
      AppLanguage.de: 'Zeit',
      AppLanguage.es: 'Hora',
      AppLanguage.ar: 'الوقت',
    },
    'date': {
      AppLanguage.en: 'Date',
      AppLanguage.tr: 'Tarih',
      AppLanguage.de: 'Datum',
      AppLanguage.es: 'Fecha',
      AppLanguage.ar: 'التاريخ',
    },
    'today': {
      AppLanguage.en: 'Today',
      AppLanguage.tr: 'Bugün',
      AppLanguage.de: 'Heute',
      AppLanguage.es: 'Hoy',
      AppLanguage.ar: 'اليوم',
    },
    'tomorrow': {
      AppLanguage.en: 'Tomorrow',
      AppLanguage.tr: 'Yarın',
      AppLanguage.de: 'Morgen',
      AppLanguage.es: 'Mañana',
      AppLanguage.ar: 'غدًا',
    },
    'days': {
      AppLanguage.en: 'days',
      AppLanguage.tr: 'gün',
      AppLanguage.de: 'Tage',
      AppLanguage.es: 'días',
      AppLanguage.ar: 'أيام',
    },
    'day': {
      AppLanguage.en: 'day',
      AppLanguage.tr: 'gün',
      AppLanguage.de: 'Tag',
      AppLanguage.es: 'día',
      AppLanguage.ar: 'يوم',
    },
    'week': {
      AppLanguage.en: 'week',
      AppLanguage.tr: 'hafta',
      AppLanguage.de: 'Woche',
      AppLanguage.es: 'semana',
      AppLanguage.ar: 'أسبوع',
    },
    'weeks': {
      AppLanguage.en: 'weeks',
      AppLanguage.tr: 'hafta',
      AppLanguage.de: 'Wochen',
      AppLanguage.es: 'semanas',
      AppLanguage.ar: 'أسابيع',
    },
    'month': {
      AppLanguage.en: 'month',
      AppLanguage.tr: 'ay',
      AppLanguage.de: 'Monat',
      AppLanguage.es: 'mes',
      AppLanguage.ar: 'شهر',
    },
    'months': {
      AppLanguage.en: 'months',
      AppLanguage.tr: 'ay',
      AppLanguage.de: 'Monate',
      AppLanguage.es: 'meses',
      AppLanguage.ar: 'أشهر',
    },
    'year': {
      AppLanguage.en: 'year',
      AppLanguage.tr: 'yıl',
      AppLanguage.de: 'Jahr',
      AppLanguage.es: 'año',
      AppLanguage.ar: 'سنة',
    },
    'years': {
      AppLanguage.en: 'years',
      AppLanguage.tr: 'yıl',
      AppLanguage.de: 'Jahre',
      AppLanguage.es: 'años',
      AppLanguage.ar: 'سنوات',
    },
    'select_range': {
      AppLanguage.en: 'Select Range',
      AppLanguage.tr: 'Süre Seç',
      AppLanguage.de: 'Zeitraum wählen',
      AppLanguage.es: 'Seleccionar Rango',
      AppLanguage.ar: 'اختر النطاق',
    },
    'date_time': {
      AppLanguage.en: 'Date & Time',
      AppLanguage.tr: 'Tarih ve Saat',
      AppLanguage.de: 'Datum & Zeit',
      AppLanguage.es: 'Fecha y Hora',
      AppLanguage.ar: 'التاريخ والوقت',
    },
    
    // ============ TABS ============
    'upcoming_tab': {
      AppLanguage.en: 'Upcoming',
      AppLanguage.tr: 'Yaklaşan',
      AppLanguage.de: 'Anstehend',
      AppLanguage.es: 'Próximos',
      AppLanguage.ar: 'القادمة',
    },
    'history_tab': {
      AppLanguage.en: 'History',
      AppLanguage.tr: 'Geçmiş',
      AppLanguage.de: 'Verlauf',
      AppLanguage.es: 'Historial',
      AppLanguage.ar: 'السجل',
    },
    'all_records': {
      AppLanguage.en: 'All Records',
      AppLanguage.tr: 'Tüm Kayıtlar',
      AppLanguage.de: 'Alle Einträge',
      AppLanguage.es: 'Todos los Registros',
      AppLanguage.ar: 'جميع السجلات',
    },
    
    // ============ HOME ============
    'upcoming_events': {
      AppLanguage.en: 'Upcoming Events',
      AppLanguage.tr: 'Yaklaşan Etkinlikler',
      AppLanguage.de: 'Anstehende Ereignisse',
      AppLanguage.es: 'Próximos Eventos',
      AppLanguage.ar: 'الأحداث القادمة',
    },
    'no_upcoming': {
      AppLanguage.en: 'No upcoming events',
      AppLanguage.tr: 'Yaklaşan etkinlik yok',
      AppLanguage.de: 'Keine anstehenden Ereignisse',
      AppLanguage.es: 'No hay eventos próximos',
      AppLanguage.ar: 'لا توجد أحداث قادمة',
    },
    'no_history': {
      AppLanguage.en: 'No history',
      AppLanguage.tr: 'Geçmiş yok',
      AppLanguage.de: 'Kein Verlauf',
      AppLanguage.es: 'Sin historial',
      AppLanguage.ar: 'لا يوجد سجل',
    },
    'no_records': {
      AppLanguage.en: 'No records',
      AppLanguage.tr: 'Kayıt yok',
      AppLanguage.de: 'Keine Einträge',
      AppLanguage.es: 'Sin registros',
      AppLanguage.ar: 'لا توجد سجلات',
    },
    'all': {
      AppLanguage.en: 'All',
      AppLanguage.tr: 'Tümü',
      AppLanguage.de: 'Alle',
      AppLanguage.es: 'Todos',
      AppLanguage.ar: 'الكل',
    },
    'good_morning': {
      AppLanguage.en: 'Good morning',
      AppLanguage.tr: 'Günaydın',
      AppLanguage.de: 'Guten Morgen',
      AppLanguage.es: 'Buenos días',
      AppLanguage.ar: 'صباح الخير',
    },
    'good_afternoon': {
      AppLanguage.en: 'Good afternoon',
      AppLanguage.tr: 'İyi günler',
      AppLanguage.de: 'Guten Tag',
      AppLanguage.es: 'Buenas tardes',
      AppLanguage.ar: 'مساء الخير',
    },
    'good_evening': {
      AppLanguage.en: 'Good evening',
      AppLanguage.tr: 'İyi akşamlar',
      AppLanguage.de: 'Guten Abend',
      AppLanguage.es: 'Buenas noches',
      AppLanguage.ar: 'مساء الخير',
    },
    
    // ============ WEIGHT ============
    'weight': {
      AppLanguage.en: 'Weight',
      AppLanguage.tr: 'Kilo',
      AppLanguage.de: 'Gewicht',
      AppLanguage.es: 'Peso',
      AppLanguage.ar: 'الوزن',
    },
    'add_weight': {
      AppLanguage.en: 'Add Weight',
      AppLanguage.tr: 'Kilo Ekle',
      AppLanguage.de: 'Gewicht hinzufügen',
      AppLanguage.es: 'Añadir Peso',
      AppLanguage.ar: 'إضافة الوزن',
    },
    'weight_history': {
      AppLanguage.en: 'Weight History',
      AppLanguage.tr: 'Kilo Geçmişi',
      AppLanguage.de: 'Gewichtsverlauf',
      AppLanguage.es: 'Historial de Peso',
      AppLanguage.ar: 'سجل الوزن',
    },
    'current_weight': {
      AppLanguage.en: 'Current Weight',
      AppLanguage.tr: 'Güncel Kilo',
      AppLanguage.de: 'Aktuelles Gewicht',
      AppLanguage.es: 'Peso Actual',
      AppLanguage.ar: 'الوزن الحالي',
    },
    'last_6_months': {
      AppLanguage.en: 'Last 6 Months',
      AppLanguage.tr: 'Son 6 Ay',
      AppLanguage.de: 'Letzte 6 Monate',
      AppLanguage.es: 'Últimos 6 meses',
      AppLanguage.ar: 'آخر 6 أشهر',
    },
    'add_first_weight': {
      AppLanguage.en: 'Add the first weight record',
      AppLanguage.tr: 'İlk kilo kaydını ekleyin',
      AppLanguage.de: 'Ersten Gewichtseintrag hinzufügen',
      AppLanguage.es: 'Añade el primer registro de peso',
      AppLanguage.ar: 'أضف أول سجل وزن',
    },
    'example': {
      AppLanguage.en: 'Example',
      AppLanguage.tr: 'Örnek',
      AppLanguage.de: 'Beispiel',
      AppLanguage.es: 'Ejemplo',
      AppLanguage.ar: 'مثال',
    },
    'no_weight_records': {
      AppLanguage.en: 'No weight records',
      AppLanguage.tr: 'Kilo kaydı yok',
      AppLanguage.de: 'Keine Gewichtseinträge',
      AppLanguage.es: 'Sin registros de peso',
      AppLanguage.ar: 'لا توجد سجلات وزن',
    },
    
    // ============ SUB-TYPES ============
    'dry_food': {
      AppLanguage.en: 'Dry Food',
      AppLanguage.tr: 'Kuru Mama',
      AppLanguage.de: 'Trockenfutter',
      AppLanguage.es: 'Comida Seca',
      AppLanguage.ar: 'طعام جاف',
    },
    'wet_food': {
      AppLanguage.en: 'Wet Food',
      AppLanguage.tr: 'Yaş Mama',
      AppLanguage.de: 'Nassfutter',
      AppLanguage.es: 'Comida Húmeda',
      AppLanguage.ar: 'طعام رطب',
    },
    'supplement': {
      AppLanguage.en: 'Supplement',
      AppLanguage.tr: 'Takviye',
      AppLanguage.de: 'Ergänzung',
      AppLanguage.es: 'Suplemento',
      AppLanguage.ar: 'مكمل',
    },
    'treat': {
      AppLanguage.en: 'Treat',
      AppLanguage.tr: 'Ödül Maması',
      AppLanguage.de: 'Leckerli',
      AppLanguage.es: 'Premio',
      AppLanguage.ar: 'مكافأة',
    },
    'internal_parasite': {
      AppLanguage.en: 'Internal Parasite',
      AppLanguage.tr: 'İç Parazit',
      AppLanguage.de: 'Innere Parasiten',
      AppLanguage.es: 'Parásito Interno',
      AppLanguage.ar: 'طفيلي داخلي',
    },
    'external_parasite': {
      AppLanguage.en: 'External Parasite',
      AppLanguage.tr: 'Dış Parazit',
      AppLanguage.de: 'Äußere Parasiten',
      AppLanguage.es: 'Parásito Externo',
      AppLanguage.ar: 'طفيلي خارجي',
    },
    'antibiotic': {
      AppLanguage.en: 'Antibiotic',
      AppLanguage.tr: 'Antibiyotik',
      AppLanguage.de: 'Antibiotikum',
      AppLanguage.es: 'Antibiótico',
      AppLanguage.ar: 'مضاد حيوي',
    },
    'vitamin': {
      AppLanguage.en: 'Vitamin',
      AppLanguage.tr: 'Vitamin',
      AppLanguage.de: 'Vitamin',
      AppLanguage.es: 'Vitamina',
      AppLanguage.ar: 'فيتامين',
    },
    'checkup': {
      AppLanguage.en: 'Check-up',
      AppLanguage.tr: 'Kontrol',
      AppLanguage.de: 'Untersuchung',
      AppLanguage.es: 'Revisión',
      AppLanguage.ar: 'فحص',
    },
    'emergency': {
      AppLanguage.en: 'Emergency',
      AppLanguage.tr: 'Acil',
      AppLanguage.de: 'Notfall',
      AppLanguage.es: 'Emergencia',
      AppLanguage.ar: 'طوارئ',
    },
    'surgery': {
      AppLanguage.en: 'Surgery',
      AppLanguage.tr: 'Ameliyat',
      AppLanguage.de: 'Operation',
      AppLanguage.es: 'Cirugía',
      AppLanguage.ar: 'جراحة',
    },
    'dental': {
      AppLanguage.en: 'Dental',
      AppLanguage.tr: 'Diş',
      AppLanguage.de: 'Zahn',
      AppLanguage.es: 'Dental',
      AppLanguage.ar: 'أسنان',
    },
    'other': {
      AppLanguage.en: 'Other',
      AppLanguage.tr: 'Diğer',
      AppLanguage.de: 'Andere',
      AppLanguage.es: 'Otro',
      AppLanguage.ar: 'آخر',
    },
    
    // ============ VACCINES ============
    'vaccine_fvrcp': {
      AppLanguage.en: 'FVRCP (Core)',
      AppLanguage.tr: 'Karma Aşı (FVRCP)',
      AppLanguage.de: 'FVRCP (Grundimpfung)',
      AppLanguage.es: 'FVRCP (Básica)',
      AppLanguage.ar: 'لقاح FVRCP',
    },
    'vaccine_rabies': {
      AppLanguage.en: 'Rabies',
      AppLanguage.tr: 'Kuduz Aşısı',
      AppLanguage.de: 'Tollwut',
      AppLanguage.es: 'Rabia',
      AppLanguage.ar: 'داء الكلب',
    },
    'vaccine_felv': {
      AppLanguage.en: 'FeLV (Leukemia)',
      AppLanguage.tr: 'Lösemi Aşısı (FeLV)',
      AppLanguage.de: 'FeLV (Leukämie)',
      AppLanguage.es: 'FeLV (Leucemia)',
      AppLanguage.ar: 'لقاح اللوكيميا',
    },
    'vaccine_fip': {
      AppLanguage.en: 'FIP',
      AppLanguage.tr: 'FIP Aşısı',
      AppLanguage.de: 'FIP',
      AppLanguage.es: 'FIP',
      AppLanguage.ar: 'FIP',
    },
    'vaccine_other': {
      AppLanguage.en: 'Other Vaccine',
      AppLanguage.tr: 'Diğer Aşı',
      AppLanguage.de: 'Andere Impfung',
      AppLanguage.es: 'Otra Vacuna',
      AppLanguage.ar: 'لقاح آخر',
    },
    
    // ============ SETTINGS ============
    'language': {
      AppLanguage.en: 'Language',
      AppLanguage.tr: 'Dil',
      AppLanguage.de: 'Sprache',
      AppLanguage.es: 'Idioma',
      AppLanguage.ar: 'اللغة',
    },
    'english': {
      AppLanguage.en: 'English',
      AppLanguage.tr: 'İngilizce',
      AppLanguage.de: 'Englisch',
      AppLanguage.es: 'Inglés',
      AppLanguage.ar: 'الإنجليزية',
    },
    'turkish': {
      AppLanguage.en: 'Turkish',
      AppLanguage.tr: 'Türkçe',
      AppLanguage.de: 'Türkisch',
      AppLanguage.es: 'Turco',
      AppLanguage.ar: 'التركية',
    },
    'german': {
      AppLanguage.en: 'German',
      AppLanguage.tr: 'Almanca',
      AppLanguage.de: 'Deutsch',
      AppLanguage.es: 'Alemán',
      AppLanguage.ar: 'الألمانية',
    },
    'spanish': {
      AppLanguage.en: 'Spanish',
      AppLanguage.tr: 'İspanyolca',
      AppLanguage.de: 'Spanisch',
      AppLanguage.es: 'Español',
      AppLanguage.ar: 'الإسبانية',
    },
    'arabic': {
      AppLanguage.en: 'Arabic',
      AppLanguage.tr: 'Arapça',
      AppLanguage.de: 'Arabisch',
      AppLanguage.es: 'Árabe',
      AppLanguage.ar: 'العربية',
    },
    'theme': {
      AppLanguage.en: 'Theme',
      AppLanguage.tr: 'Tema',
      AppLanguage.de: 'Design',
      AppLanguage.es: 'Tema',
      AppLanguage.ar: 'المظهر',
    },
    'theme_light': {
      AppLanguage.en: 'Light',
      AppLanguage.tr: 'Açık',
      AppLanguage.de: 'Hell',
      AppLanguage.es: 'Claro',
      AppLanguage.ar: 'فاتح',
    },
    'theme_dark': {
      AppLanguage.en: 'Dark',
      AppLanguage.tr: 'Koyu',
      AppLanguage.de: 'Dunkel',
      AppLanguage.es: 'Oscuro',
      AppLanguage.ar: 'داكن',
    },
    'theme_system': {
      AppLanguage.en: 'System',
      AppLanguage.tr: 'Sistem',
      AppLanguage.de: 'System',
      AppLanguage.es: 'Sistema',
      AppLanguage.ar: 'النظام',
    },
    'notifications': {
      AppLanguage.en: 'Notifications',
      AppLanguage.tr: 'Bildirimler',
      AppLanguage.de: 'Benachrichtigungen',
      AppLanguage.es: 'Notificaciones',
      AppLanguage.ar: 'الإشعارات',
    },
    'notification_settings': {
      AppLanguage.en: 'Notification Settings',
      AppLanguage.tr: 'Bildirim Ayarları',
      AppLanguage.de: 'Benachrichtigungseinstellungen',
      AppLanguage.es: 'Ajustes de Notificación',
      AppLanguage.ar: 'إعدادات الإشعارات',
    },
    'about': {
      AppLanguage.en: 'About',
      AppLanguage.tr: 'Hakkında',
      AppLanguage.de: 'Über',
      AppLanguage.es: 'Acerca de',
      AppLanguage.ar: 'حول',
    },
    'about_app': {
      AppLanguage.en: 'About DOTCAT',
      AppLanguage.tr: 'DOTCAT Hakkında',
      AppLanguage.de: 'Über DOTCAT',
      AppLanguage.es: 'Acerca de DOTCAT',
      AppLanguage.ar: 'حول DOTCAT',
    },
    'privacy_policy': {
      AppLanguage.en: 'Privacy Policy',
      AppLanguage.tr: 'Gizlilik Politikası',
      AppLanguage.de: 'Datenschutzrichtlinie',
      AppLanguage.es: 'Política de Privacidad',
      AppLanguage.ar: 'سياسة الخصوصية',
    },
    'appearance': {
      AppLanguage.en: 'Appearance',
      AppLanguage.tr: 'Görünüm',
      AppLanguage.de: 'Erscheinungsbild',
      AppLanguage.es: 'Apariencia',
      AppLanguage.ar: 'المظهر',
    },
    
    // ============ BUTTONS ============
    'save': {
      AppLanguage.en: 'Save',
      AppLanguage.tr: 'Kaydet',
      AppLanguage.de: 'Speichern',
      AppLanguage.es: 'Guardar',
      AppLanguage.ar: 'حفظ',
    },
    'cancel': {
      AppLanguage.en: 'Cancel',
      AppLanguage.tr: 'İptal',
      AppLanguage.de: 'Abbrechen',
      AppLanguage.es: 'Cancelar',
      AppLanguage.ar: 'إلغاء',
    },
    'delete': {
      AppLanguage.en: 'Delete',
      AppLanguage.tr: 'Sil',
      AppLanguage.de: 'Löschen',
      AppLanguage.es: 'Eliminar',
      AppLanguage.ar: 'حذف',
    },
    'edit': {
      AppLanguage.en: 'Edit',
      AppLanguage.tr: 'Düzenle',
      AppLanguage.de: 'Bearbeiten',
      AppLanguage.es: 'Editar',
      AppLanguage.ar: 'تعديل',
    },
    'close': {
      AppLanguage.en: 'Close',
      AppLanguage.tr: 'Kapat',
      AppLanguage.de: 'Schließen',
      AppLanguage.es: 'Cerrar',
      AppLanguage.ar: 'إغلاق',
    },
    'continue_btn': {
      AppLanguage.en: 'Continue',
      AppLanguage.tr: 'Devam',
      AppLanguage.de: 'Weiter',
      AppLanguage.es: 'Continuar',
      AppLanguage.ar: 'متابعة',
    },
    'skip': {
      AppLanguage.en: 'Skip',
      AppLanguage.tr: 'Atla',
      AppLanguage.de: 'Überspringen',
      AppLanguage.es: 'Omitir',
      AppLanguage.ar: 'تخطي',
    },
    'next': {
      AppLanguage.en: 'Next',
      AppLanguage.tr: 'İleri',
      AppLanguage.de: 'Weiter',
      AppLanguage.es: 'Siguiente',
      AppLanguage.ar: 'التالي',
    },
    'get_started': {
      AppLanguage.en: 'Get Started',
      AppLanguage.tr: 'Başla',
      AppLanguage.de: 'Loslegen',
      AppLanguage.es: 'Empezar',
      AppLanguage.ar: 'ابدأ',
    },
    'select_all': {
      AppLanguage.en: 'Select All',
      AppLanguage.tr: 'Tümünü Seç',
      AppLanguage.de: 'Alle auswählen',
      AppLanguage.es: 'Seleccionar Todo',
      AppLanguage.ar: 'تحديد الكل',
    },
    'deselect_all': {
      AppLanguage.en: 'Deselect All',
      AppLanguage.tr: 'Seçimi Kaldır',
      AppLanguage.de: 'Alle abwählen',
      AppLanguage.es: 'Deseleccionar Todo',
      AppLanguage.ar: 'إلغاء تحديد الكل',
    },
    
    // ============ ONBOARDING ============
    'onboarding_title_1': {
      AppLanguage.en: 'Welcome to DOTCAT',
      AppLanguage.tr: 'DOTCAT\'a Hoş Geldiniz',
      AppLanguage.de: 'Willkommen bei DOTCAT',
      AppLanguage.es: 'Bienvenido a DOTCAT',
      AppLanguage.ar: 'مرحبًا بك في DOTCAT',
    },
    'onboarding_desc_1': {
      AppLanguage.en: 'Your personal cat care assistant',
      AppLanguage.tr: 'Kişisel kedi bakım asistanınız',
      AppLanguage.de: 'Ihr persönlicher Katzenpflege-Assistent',
      AppLanguage.es: 'Tu asistente personal de cuidado de gatos',
      AppLanguage.ar: 'مساعدك الشخصي لرعاية القطط',
    },
    'onboarding_title_2': {
      AppLanguage.en: 'Health Records',
      AppLanguage.tr: 'Sağlık Kayıtları',
      AppLanguage.de: 'Gesundheitsakten',
      AppLanguage.es: 'Registros de Salud',
      AppLanguage.ar: 'السجلات الصحية',
    },
    'onboarding_desc_2': {
      AppLanguage.en: 'Track all health records',
      AppLanguage.tr: 'Tüm sağlık kayıtlarını takip edin',
      AppLanguage.de: 'Alle Gesundheitsakten verfolgen',
      AppLanguage.es: 'Sigue todos los registros de salud',
      AppLanguage.ar: 'تتبع جميع السجلات الصحية',
    },
    'onboarding_title_3': {
      AppLanguage.en: 'Smart Reminders',
      AppLanguage.tr: 'Akıllı Hatırlatıcılar',
      AppLanguage.de: 'Intelligente Erinnerungen',
      AppLanguage.es: 'Recordatorios Inteligentes',
      AppLanguage.ar: 'تذكيرات ذكية',
    },
    'onboarding_desc_3': {
      AppLanguage.en: 'Never miss important dates',
      AppLanguage.tr: 'Önemli tarihleri kaçırmayın',
      AppLanguage.de: 'Verpassen Sie nie wichtige Termine',
      AppLanguage.es: 'Nunca pierdas fechas importantes',
      AppLanguage.ar: 'لا تفوت المواعيد المهمة',
    },
    'onboarding_title_4': {
      AppLanguage.en: 'Complete History',
      AppLanguage.tr: 'Tam Geçmiş',
      AppLanguage.de: 'Vollständige Historie',
      AppLanguage.es: 'Historial Completo',
      AppLanguage.ar: 'السجل الكامل',
    },
    'onboarding_desc_4': {
      AppLanguage.en: 'View complete care history',
      AppLanguage.tr: 'Tüm bakım geçmişini görün',
      AppLanguage.de: 'Komplette Pflegehistorie anzeigen',
      AppLanguage.es: 'Ver historial completo de cuidados',
      AppLanguage.ar: 'عرض سجل الرعاية الكامل',
    },
    'onboarding_title_swipe': {
      AppLanguage.en: 'Quick Actions',
      AppLanguage.tr: 'Hızlı İşlemler',
      AppLanguage.de: 'Schnellaktionen',
      AppLanguage.es: 'Acciones Rápidas',
      AppLanguage.ar: 'إجراءات سريعة',
    },
    'onboarding_desc_swipe': {
      AppLanguage.en: 'Swipe right to complete',
      AppLanguage.tr: 'Tamamlamak için sağa kaydırın',
      AppLanguage.de: 'Nach rechts wischen zum Abschließen',
      AppLanguage.es: 'Desliza a la derecha para completar',
      AppLanguage.ar: 'اسحب يمينًا للإكمال',
    },
    
    // ============ FEATURES ============
    'feature_multi_cat': {
      AppLanguage.en: 'Multiple cats',
      AppLanguage.tr: 'Çoklu kedi takibi',
      AppLanguage.de: 'Mehrere Katzen',
      AppLanguage.es: 'Múltiples gatos',
      AppLanguage.ar: 'قطط متعددة',
    },
    'feature_photo': {
      AppLanguage.en: 'Add photos',
      AppLanguage.tr: 'Fotoğraf ekle',
      AppLanguage.de: 'Fotos hinzufügen',
      AppLanguage.es: 'Añadir fotos',
      AppLanguage.ar: 'إضافة صور',
    },
    'feature_profile': {
      AppLanguage.en: 'Cat profiles',
      AppLanguage.tr: 'Kedi profilleri',
      AppLanguage.de: 'Katzenprofile',
      AppLanguage.es: 'Perfiles de gatos',
      AppLanguage.ar: 'ملفات القطط',
    },
    'feature_vaccine': {
      AppLanguage.en: 'Vaccination records',
      AppLanguage.tr: 'Aşı kayıtları',
      AppLanguage.de: 'Impfaufzeichnungen',
      AppLanguage.es: 'Registros de vacunación',
      AppLanguage.ar: 'سجلات التطعيم',
    },
    'feature_medicine': {
      AppLanguage.en: 'Medicine tracking',
      AppLanguage.tr: 'İlaç takibi',
      AppLanguage.de: 'Medikamentenverfolgung',
      AppLanguage.es: 'Seguimiento de medicamentos',
      AppLanguage.ar: 'تتبع الأدوية',
    },
    'feature_vet': {
      AppLanguage.en: 'Vet visits',
      AppLanguage.tr: 'Veteriner ziyaretleri',
      AppLanguage.de: 'Tierarztbesuche',
      AppLanguage.es: 'Visitas al veterinario',
      AppLanguage.ar: 'زيارات الطبيب البيطري',
    },
    'feature_food': {
      AppLanguage.en: 'Feeding schedules',
      AppLanguage.tr: 'Mama programları',
      AppLanguage.de: 'Fütterungspläne',
      AppLanguage.es: 'Horarios de alimentación',
      AppLanguage.ar: 'جداول التغذية',
    },
    'feature_reminder': {
      AppLanguage.en: 'Custom reminders',
      AppLanguage.tr: 'Özel hatırlatıcılar',
      AppLanguage.de: 'Benutzerdefinierte Erinnerungen',
      AppLanguage.es: 'Recordatorios personalizados',
      AppLanguage.ar: 'تذكيرات مخصصة',
    },
    'feature_repeat': {
      AppLanguage.en: 'Repeating events',
      AppLanguage.tr: 'Tekrarlayan etkinlikler',
      AppLanguage.de: 'Wiederholende Ereignisse',
      AppLanguage.es: 'Eventos repetitivos',
      AppLanguage.ar: 'أحداث متكررة',
    },
    'feature_notify': {
      AppLanguage.en: 'Push notifications',
      AppLanguage.tr: 'Anlık bildirimler',
      AppLanguage.de: 'Push-Benachrichtigungen',
      AppLanguage.es: 'Notificaciones push',
      AppLanguage.ar: 'إشعارات فورية',
    },
    'feature_history': {
      AppLanguage.en: 'Complete history',
      AppLanguage.tr: 'Tam geçmiş',
      AppLanguage.de: 'Vollständiger Verlauf',
      AppLanguage.es: 'Historial completo',
      AppLanguage.ar: 'السجل الكامل',
    },
    'feature_filter': {
      AppLanguage.en: 'Filter by type',
      AppLanguage.tr: 'Türe göre filtrele',
      AppLanguage.de: 'Nach Typ filtern',
      AppLanguage.es: 'Filtrar por tipo',
      AppLanguage.ar: 'تصفية حسب النوع',
    },
    'feature_weight': {
      AppLanguage.en: 'Weight tracking',
      AppLanguage.tr: 'Kilo takibi',
      AppLanguage.de: 'Gewichtsverfolgung',
      AppLanguage.es: 'Seguimiento de peso',
      AppLanguage.ar: 'تتبع الوزن',
    },
    
    // ============ SWIPE HINT ============
    'swipe_hint': {
      AppLanguage.en: 'Swipe right to complete',
      AppLanguage.tr: 'Tamamlamak için sağa kaydırın',
      AppLanguage.de: 'Nach rechts wischen zum Abschließen',
      AppLanguage.es: 'Desliza a la derecha para completar',
      AppLanguage.ar: 'اسحب يمينًا للإكمال',
    },
    'tip_tap_detail': {
      AppLanguage.en: 'Tap for details',
      AppLanguage.tr: 'Detay için dokunun',
      AppLanguage.de: 'Tippen für Details',
      AppLanguage.es: 'Toca para ver detalles',
      AppLanguage.ar: 'انقر للتفاصيل',
    },
    'tip_filter': {
      AppLanguage.en: 'Use filters',
      AppLanguage.tr: 'Filtreleri kullanın',
      AppLanguage.de: 'Filter verwenden',
      AppLanguage.es: 'Usa filtros',
      AppLanguage.ar: 'استخدم الفلاتر',
    },
    'tip_range': {
      AppLanguage.en: 'Change date range',
      AppLanguage.tr: 'Tarih aralığını değiştirin',
      AppLanguage.de: 'Datumsbereich ändern',
      AppLanguage.es: 'Cambia el rango de fechas',
      AppLanguage.ar: 'تغيير نطاق التاريخ',
    },
    
    // ============ MISC ============
    'error_saving': {
      AppLanguage.en: 'Error saving',
      AppLanguage.tr: 'Kaydetme hatası',
      AppLanguage.de: 'Fehler beim Speichern',
      AppLanguage.es: 'Error al guardar',
      AppLanguage.ar: 'خطأ في الحفظ',
    },
    'select_cat_required': {
      AppLanguage.en: 'Please select a cat',
      AppLanguage.tr: 'Lütfen kedi seçin',
      AppLanguage.de: 'Bitte wählen Sie eine Katze',
      AppLanguage.es: 'Por favor seleccione un gato',
      AppLanguage.ar: 'الرجاء اختيار قطة',
    },
    'enter_title': {
      AppLanguage.en: 'Enter title',
      AppLanguage.tr: 'Başlık girin',
      AppLanguage.de: 'Titel eingeben',
      AppLanguage.es: 'Ingrese título',
      AppLanguage.ar: 'أدخل العنوان',
    },
    'more': {
      AppLanguage.en: 'more',
      AppLanguage.tr: 'daha',
      AppLanguage.de: 'mehr',
      AppLanguage.es: 'más',
      AppLanguage.ar: 'المزيد',
    },
    'remind_me': {
      AppLanguage.en: 'Remind me',
      AppLanguage.tr: 'Hatırlat',
      AppLanguage.de: 'Erinnere mich',
      AppLanguage.es: 'Recuérdame',
      AppLanguage.ar: 'ذكرني',
    },
    'notification_time': {
      AppLanguage.en: 'Notification time',
      AppLanguage.tr: 'Bildirim saati',
      AppLanguage.de: 'Benachrichtigungszeit',
      AppLanguage.es: 'Hora de notificación',
      AppLanguage.ar: 'وقت الإشعار',
    },
    'no_cats_yet': {
      AppLanguage.en: 'No cats yet',
      AppLanguage.tr: 'Henüz kedi yok',
      AppLanguage.de: 'Noch keine Katzen',
      AppLanguage.es: 'Sin gatos aún',
      AppLanguage.ar: 'لا توجد قطط بعد',
    },
    'add_your_cat': {
      AppLanguage.en: 'Add your first cat to get started',
      AppLanguage.tr: 'Başlamak için ilk kedinizi ekleyin',
      AppLanguage.de: 'Fügen Sie Ihre erste Katze hinzu',
      AppLanguage.es: 'Añade tu primer gato',
      AppLanguage.ar: 'أضف قطتك الأولى للبدء',
    },
    'add_cat_first': {
      AppLanguage.en: 'Please add a cat first',
      AppLanguage.tr: 'Lütfen önce kedi ekleyin',
      AppLanguage.de: 'Bitte fügen Sie zuerst eine Katze hinzu',
      AppLanguage.es: 'Por favor añade un gato primero',
      AppLanguage.ar: 'الرجاء إضافة قطة أولاً',
    },
    'grooming_type': {
      AppLanguage.en: 'Grooming Type',
      AppLanguage.tr: 'Bakım Türü',
      AppLanguage.de: 'Pflegeart',
      AppLanguage.es: 'Tipo de Aseo',
      AppLanguage.ar: 'نوع العناية',
    },
    'edit_photo': {
      AppLanguage.en: 'Edit Photo',
      AppLanguage.tr: 'Fotoğrafı Düzenle',
      AppLanguage.de: 'Foto bearbeiten',
      AppLanguage.es: 'Editar Foto',
      AppLanguage.ar: 'تعديل الصورة',
    },
    'swipe_hint': {
      AppLanguage.en: 'Swipe right to complete, left to undo',
      AppLanguage.tr: 'Tamamlamak için sağa, geri almak için sola kaydır',
      AppLanguage.de: 'Nach rechts wischen zum Abschließen, nach links zum Rückgängig',
      AppLanguage.es: 'Desliza a la derecha para completar, a la izquierda para deshacer',
      AppLanguage.ar: 'اسحب لليمين للإكمال، لليسار للتراجع',
    },
    'completed_events': {
      AppLanguage.en: 'Completed',
      AppLanguage.tr: 'Tamamlananlar',
      AppLanguage.de: 'Abgeschlossen',
      AppLanguage.es: 'Completados',
      AppLanguage.ar: 'المكتملة',
    },
    'mark_completed': {
      AppLanguage.en: 'Complete',
      AppLanguage.tr: 'Tamamla',
      AppLanguage.de: 'Erledigt',
      AppLanguage.es: 'Completar',
      AppLanguage.ar: 'إكمال',
    },
    'mark_pending': {
      AppLanguage.en: 'Undo',
      AppLanguage.tr: 'Geri Al',
      AppLanguage.de: 'Rückgängig',
      AppLanguage.es: 'Deshacer',
      AppLanguage.ar: 'تراجع',
    },
    'days_ago': {
      AppLanguage.en: 'days ago',
      AppLanguage.tr: 'gün önce',
      AppLanguage.de: 'Tage her',
      AppLanguage.es: 'días atrás',
      AppLanguage.ar: 'أيام مضت',
    },
    'marked_pending': {
      AppLanguage.en: 'Marked as pending',
      AppLanguage.tr: 'Bekliyor olarak işaretlendi',
      AppLanguage.de: 'Als ausstehend markiert',
      AppLanguage.es: 'Marcado como pendiente',
      AppLanguage.ar: 'تم وضع علامة قيد الانتظار',
    },
    'this_week': {
      AppLanguage.en: 'This Week',
      AppLanguage.tr: 'Bu Hafta',
      AppLanguage.de: 'Diese Woche',
      AppLanguage.es: 'Esta Semana',
      AppLanguage.ar: 'هذا الأسبوع',
    },
    'this_month': {
      AppLanguage.en: 'This Month',
      AppLanguage.tr: 'Bu Ay',
      AppLanguage.de: 'Diesen Monat',
      AppLanguage.es: 'Este Mes',
      AppLanguage.ar: 'هذا الشهر',
    },
    'three_months': {
      AppLanguage.en: '3 Months',
      AppLanguage.tr: '3 Ay',
      AppLanguage.de: '3 Monate',
      AppLanguage.es: '3 Meses',
      AppLanguage.ar: '3 أشهر',
    },
    'this_year': {
      AppLanguage.en: 'This Year',
      AppLanguage.tr: 'Bu Yıl',
      AppLanguage.de: 'Dieses Jahr',
      AppLanguage.es: 'Este Año',
      AppLanguage.ar: 'هذا العام',
    },
    'calendar': {
      AppLanguage.en: 'Calendar',
      AppLanguage.tr: 'Takvim',
      AppLanguage.de: 'Kalender',
      AppLanguage.es: 'Calendario',
      AppLanguage.ar: 'التقويم',
    },
    'add_weight_reminder': {
      AppLanguage.en: 'Add weight reminder',
      AppLanguage.tr: 'Kilo ölçüm hatırlatıcısı ekle',
      AppLanguage.de: 'Gewichtserinnerung hinzufügen',
      AppLanguage.es: 'Añadir recordatorio de peso',
      AppLanguage.ar: 'إضافة تذكير بالوزن',
    },
    'weight_tracking': {
      AppLanguage.en: 'Weight Tracking',
      AppLanguage.tr: 'Kilo Takibi',
      AppLanguage.de: 'Gewichtsverfolgung',
      AppLanguage.es: 'Seguimiento de Peso',
      AppLanguage.ar: 'تتبع الوزن',
    },
    'weight_trend': {
      AppLanguage.en: 'Weight Trend',
      AppLanguage.tr: 'Kilo Trendi',
      AppLanguage.de: 'Gewichtstrend',
      AppLanguage.es: 'Tendencia de Peso',
      AppLanguage.ar: 'اتجاه الوزن',
    },
    'overdue_events': {
      AppLanguage.en: 'Overdue',
      AppLanguage.tr: 'Süresi Geçenler',
      AppLanguage.de: 'Überfällig',
      AppLanguage.es: 'Atrasados',
      AppLanguage.ar: 'متأخرة',
    },
    'select_range': {
      AppLanguage.en: 'Select Range',
      AppLanguage.tr: 'Süre Seç',
      AppLanguage.de: 'Bereich wählen',
      AppLanguage.es: 'Seleccionar Rango',
      AppLanguage.ar: 'اختر النطاق',
    },
    'no_completed': {
      AppLanguage.en: 'No completed events yet',
      AppLanguage.tr: 'Henüz tamamlanan etkinlik yok',
      AppLanguage.de: 'Noch keine abgeschlossenen Ereignisse',
      AppLanguage.es: 'Aún no hay eventos completados',
      AppLanguage.ar: 'لا توجد أحداث مكتملة بعد',
    },
    'login_data_note': {
      AppLanguage.en: 'Sign in to keep your data safe and never lose it',
      AppLanguage.tr: 'Verilerinizi kaybetmemek için giriş yapın',
      AppLanguage.de: 'Melden Sie sich an, um Ihre Daten zu schützen',
      AppLanguage.es: 'Inicia sesión para no perder tus datos',
      AppLanguage.ar: 'سجل الدخول للحفاظ على بياناتك',
    },
    'synced': {
      AppLanguage.en: 'Synced',
      AppLanguage.tr: 'Senkronize',
      AppLanguage.de: 'Synchronisiert',
      AppLanguage.es: 'Sincronizado',
      AppLanguage.ar: 'متزامن',
    },
    'enable_notifications': {
      AppLanguage.en: 'Enable Notifications',
      AppLanguage.tr: 'Bildirimleri Etkinleştir',
      AppLanguage.de: 'Benachrichtigungen aktivieren',
      AppLanguage.es: 'Activar Notificaciones',
      AppLanguage.ar: 'تفعيل الإشعارات',
    },
    'notification_desc': {
      AppLanguage.en: 'Get reminders for your pet care tasks',
      AppLanguage.tr: 'Evcil hayvan bakım görevleri için hatırlatıcı alın',
      AppLanguage.de: 'Erhalten Sie Erinnerungen für Ihre Haustierpflege',
      AppLanguage.es: 'Recibe recordatorios para el cuidado de tu mascota',
      AppLanguage.ar: 'احصل على تذكيرات لمهام رعاية حيوانك الأليف',
    },
    'remind_before': {
      AppLanguage.en: 'Remind Before',
      AppLanguage.tr: 'Önceden Hatırlat',
      AppLanguage.de: 'Vorher erinnern',
      AppLanguage.es: 'Recordar Antes',
      AppLanguage.ar: 'التذكير قبل',
    },
    '1_hour_before': {
      AppLanguage.en: '1 hour before',
      AppLanguage.tr: '1 saat önce',
      AppLanguage.de: '1 Stunde vorher',
      AppLanguage.es: '1 hora antes',
      AppLanguage.ar: 'قبل ساعة واحدة',
    },
    '2_hours_before': {
      AppLanguage.en: '2 hours before',
      AppLanguage.tr: '2 saat önce',
      AppLanguage.de: '2 Stunden vorher',
      AppLanguage.es: '2 horas antes',
      AppLanguage.ar: 'قبل ساعتين',
    },
    '6_hours_before': {
      AppLanguage.en: '6 hours before',
      AppLanguage.tr: '6 saat önce',
      AppLanguage.de: '6 Stunden vorher',
      AppLanguage.es: '6 horas antes',
      AppLanguage.ar: 'قبل 6 ساعات',
    },
    '12_hours_before': {
      AppLanguage.en: '12 hours before',
      AppLanguage.tr: '12 saat önce',
      AppLanguage.de: '12 Stunden vorher',
      AppLanguage.es: '12 horas antes',
      AppLanguage.ar: 'قبل 12 ساعة',
    },
    '1_day_before': {
      AppLanguage.en: '1 day before',
      AppLanguage.tr: '1 gün önce',
      AppLanguage.de: '1 Tag vorher',
      AppLanguage.es: '1 día antes',
      AppLanguage.ar: 'قبل يوم واحد',
    },
    '2_days_before': {
      AppLanguage.en: '2 days before',
      AppLanguage.tr: '2 gün önce',
      AppLanguage.de: '2 Tage vorher',
      AppLanguage.es: '2 días antes',
      AppLanguage.ar: 'قبل يومين',
    },
    '1_week_before': {
      AppLanguage.en: '1 week before',
      AppLanguage.tr: '1 hafta önce',
      AppLanguage.de: '1 Woche vorher',
      AppLanguage.es: '1 semana antes',
      AppLanguage.ar: 'قبل أسبوع واحد',
    },
    'hours_before': {
      AppLanguage.en: 'hours before',
      AppLanguage.tr: 'saat önce',
      AppLanguage.de: 'Stunden vorher',
      AppLanguage.es: 'horas antes',
      AppLanguage.ar: 'ساعات قبل',
    },
    'notification_sound': {
      AppLanguage.en: 'Sound',
      AppLanguage.tr: 'Ses',
      AppLanguage.de: 'Ton',
      AppLanguage.es: 'Sonido',
      AppLanguage.ar: 'الصوت',
    },
    'notification_vibration': {
      AppLanguage.en: 'Vibration',
      AppLanguage.tr: 'Titreşim',
      AppLanguage.de: 'Vibration',
      AppLanguage.es: 'Vibración',
      AppLanguage.ar: 'الاهتزاز',
    },
    'test_notification': {
      AppLanguage.en: 'Test Notification',
      AppLanguage.tr: 'Test Bildirimi',
      AppLanguage.de: 'Test-Benachrichtigung',
      AppLanguage.es: 'Notificación de Prueba',
      AppLanguage.ar: 'إشعار اختباري',
    },
    'test_notification_body': {
      AppLanguage.en: 'This is a test notification from PetCare',
      AppLanguage.tr: 'Bu PetCare\'den bir test bildirimidir',
      AppLanguage.de: 'Dies ist eine Testbenachrichtigung von PetCare',
      AppLanguage.es: 'Esta es una notificación de prueba de PetCare',
      AppLanguage.ar: 'هذا إشعار اختباري من PetCare',
    },
    'test_notification_sent': {
      AppLanguage.en: 'Test notification sent!',
      AppLanguage.tr: 'Test bildirimi gönderildi!',
      AppLanguage.de: 'Testbenachrichtigung gesendet!',
      AppLanguage.es: '¡Notificación de prueba enviada!',
      AppLanguage.ar: 'تم إرسال إشعار الاختبار!',
    },
    'notification_permission_required': {
      AppLanguage.en: 'Notification permission is required',
      AppLanguage.tr: 'Bildirim izni gerekli',
      AppLanguage.de: 'Benachrichtigungsberechtigung erforderlich',
      AppLanguage.es: 'Se requiere permiso de notificación',
      AppLanguage.ar: 'إذن الإشعار مطلوب',
    },
    'notification_permission_desc': {
      AppLanguage.en: 'To receive reminders for your pet care tasks, please enable notifications in your device settings.',
      AppLanguage.tr: 'Evcil hayvan bakım görevleriniz için hatırlatıcı almak için lütfen cihaz ayarlarınızdan bildirimleri etkinleştirin.',
      AppLanguage.de: 'Um Erinnerungen für Ihre Haustierpflegeaufgaben zu erhalten, aktivieren Sie bitte Benachrichtigungen in Ihren Geräteeinstellungen.',
      AppLanguage.es: 'Para recibir recordatorios de las tareas de cuidado de mascotas, active las notificaciones en la configuración de su dispositivo.',
      AppLanguage.ar: 'لتلقي تذكيرات لمهام رعاية حيوانك الأليف، يرجى تمكين الإشعارات في إعدادات جهازك.',
    },
    'notification_sound_type': {
      AppLanguage.en: 'Notification Sound',
      AppLanguage.tr: 'Bildirim Sesi',
      AppLanguage.de: 'Benachrichtigungston',
      AppLanguage.es: 'Sonido de Notificación',
      AppLanguage.ar: 'صوت الإشعار',
    },
    'default_sound': {
      AppLanguage.en: 'Default Sound',
      AppLanguage.tr: 'Varsayılan Ses',
      AppLanguage.de: 'Standardton',
      AppLanguage.es: 'Sonido Predeterminado',
      AppLanguage.ar: 'الصوت الافتراضي',
    },
    'cat_meow_sound': {
      AppLanguage.en: 'Cat Meow',
      AppLanguage.tr: 'Kedi Miyavlama',
      AppLanguage.de: 'Katzenmiauen',
      AppLanguage.es: 'Maullido de Gato',
      AppLanguage.ar: 'مواء القط',
    },
    'weight_check': {
      AppLanguage.en: 'Weight Check',
      AppLanguage.tr: 'Kilo Kontrolü',
      AppLanguage.de: 'Gewichtskontrolle',
      AppLanguage.es: 'Control de Peso',
      AppLanguage.ar: 'فحص الوزن',
    },
    'weight': {
      AppLanguage.en: 'Weight',
      AppLanguage.tr: 'Kilo',
      AppLanguage.de: 'Gewicht',
      AppLanguage.es: 'Peso',
      AppLanguage.ar: 'الوزن',
    },
    'filter': {
      AppLanguage.en: 'Filter',
      AppLanguage.tr: 'Filtre',
      AppLanguage.de: 'Filter',
      AppLanguage.es: 'Filtro',
      AppLanguage.ar: 'تصفية',
    },
    'continue_btn': {
      AppLanguage.en: 'Continue',
      AppLanguage.tr: 'Devam',
      AppLanguage.de: 'Weiter',
      AppLanguage.es: 'Continuar',
      AppLanguage.ar: 'متابعة',
    },
    'onboarding_welcome_tagline': {
      AppLanguage.en: 'Your complete companion for cat care',
      AppLanguage.tr: 'Kedi bakımı için eksiksiz yardımcınız',
      AppLanguage.de: 'Ihr kompletter Begleiter für die Katzenpflege',
      AppLanguage.es: 'Tu compañero completo para el cuidado de gatos',
      AppLanguage.ar: 'رفيقك الكامل لرعاية القطط',
    },
    'onboarding_vaccine_feature1': {
      AppLanguage.en: 'Track all vaccination dates',
      AppLanguage.tr: 'Tüm aşı tarihlerini takip edin',
      AppLanguage.de: 'Alle Impftermine verfolgen',
      AppLanguage.es: 'Seguimiento de todas las vacunas',
      AppLanguage.ar: 'تتبع جميع مواعيد التطعيم',
    },
    'onboarding_vaccine_feature2': {
      AppLanguage.en: 'Get reminders before due dates',
      AppLanguage.tr: 'Zamanı gelmeden hatırlatma alın',
      AppLanguage.de: 'Erinnerungen vor Fälligkeitsdaten',
      AppLanguage.es: 'Recordatorios antes de las fechas',
      AppLanguage.ar: 'احصل على تذكيرات قبل المواعيد',
    },
    'onboarding_vaccine_feature3': {
      AppLanguage.en: 'Keep vaccination history organized',
      AppLanguage.tr: 'Aşı geçmişini düzenli tutun',
      AppLanguage.de: 'Impfhistorie organisiert halten',
      AppLanguage.es: 'Mantén el historial organizado',
      AppLanguage.ar: 'حافظ على سجل التطعيم منظماً',
    },
    'onboarding_medicine_feature1': {
      AppLanguage.en: 'Daily medication reminders',
      AppLanguage.tr: 'Günlük ilaç hatırlatıcıları',
      AppLanguage.de: 'Tägliche Medikamentenerinnerungen',
      AppLanguage.es: 'Recordatorios diarios de medicación',
      AppLanguage.ar: 'تذكيرات الأدوية اليومية',
    },
    'onboarding_medicine_feature2': {
      AppLanguage.en: 'Set custom schedules',
      AppLanguage.tr: 'Özel programlar ayarlayın',
      AppLanguage.de: 'Benutzerdefinierte Zeitpläne',
      AppLanguage.es: 'Horarios personalizados',
      AppLanguage.ar: 'ضبط جداول مخصصة',
    },
    'onboarding_medicine_feature3': {
      AppLanguage.en: 'Track supplements and treatments',
      AppLanguage.tr: 'Takviye ve tedavileri takip edin',
      AppLanguage.de: 'Nahrungsergänzungen verfolgen',
      AppLanguage.es: 'Seguimiento de suplementos',
      AppLanguage.ar: 'تتبع المكملات والعلاجات',
    },
    'onboarding_vet_feature1': {
      AppLanguage.en: 'Schedule appointments easily',
      AppLanguage.tr: 'Randevuları kolayca planlayın',
      AppLanguage.de: 'Termine einfach planen',
      AppLanguage.es: 'Programa citas fácilmente',
      AppLanguage.ar: 'جدولة المواعيد بسهولة',
    },
    'onboarding_vet_feature2': {
      AppLanguage.en: 'Never miss a checkup',
      AppLanguage.tr: 'Hiçbir kontrolü kaçırmayın',
      AppLanguage.de: 'Keine Untersuchung verpassen',
      AppLanguage.es: 'No pierdas ningún chequeo',
      AppLanguage.ar: 'لا تفوت أي فحص',
    },
    'onboarding_vet_feature3': {
      AppLanguage.en: 'Keep visit notes handy',
      AppLanguage.tr: 'Ziyaret notlarını el altında tutun',
      AppLanguage.de: 'Besuchsnotizen griffbereit',
      AppLanguage.es: 'Notas de visita a mano',
      AppLanguage.ar: 'احتفظ بملاحظات الزيارة',
    },
    'onboarding_food_feature1': {
      AppLanguage.en: 'Set feeding schedules',
      AppLanguage.tr: 'Beslenme programları ayarlayın',
      AppLanguage.de: 'Fütterungspläne festlegen',
      AppLanguage.es: 'Horarios de alimentación',
      AppLanguage.ar: 'ضبط جداول التغذية',
    },
    'onboarding_food_feature2': {
      AppLanguage.en: 'Track treats and snacks',
      AppLanguage.tr: 'Ödülleri ve atıştırmalıkları takip edin',
      AppLanguage.de: 'Leckerlis verfolgen',
      AppLanguage.es: 'Seguimiento de premios',
      AppLanguage.ar: 'تتبع المكافآت',
    },
    'onboarding_food_feature3': {
      AppLanguage.en: 'Monitor diet changes',
      AppLanguage.tr: 'Diyet değişikliklerini izleyin',
      AppLanguage.de: 'Ernährungsänderungen überwachen',
      AppLanguage.es: 'Monitorear cambios de dieta',
      AppLanguage.ar: 'مراقبة تغييرات النظام الغذائي',
    },
    'onboarding_vaccine_title': {
      AppLanguage.en: 'Vaccine Tracking',
      AppLanguage.tr: 'Aşı Takibi',
      AppLanguage.de: 'Impf-Tracking',
      AppLanguage.es: 'Seguimiento de Vacunas',
      AppLanguage.ar: 'تتبع اللقاحات',
    },
    'onboarding_vaccine_desc': {
      AppLanguage.en: 'Never miss a vaccination date. Set reminders and keep your cat\'s immunization records organized.',
      AppLanguage.tr: 'Hiçbir aşı tarihini kaçırmayın. Hatırlatıcılar ayarlayın ve kedinizin aşı kayıtlarını düzenli tutun.',
      AppLanguage.de: 'Verpassen Sie nie einen Impftermin. Richten Sie Erinnerungen ein.',
      AppLanguage.es: 'Nunca pierdas una fecha de vacunación. Configura recordatorios.',
      AppLanguage.ar: 'لا تفوت أي موعد تطعيم. قم بإعداد التذكيرات.',
    },
    'onboarding_medicine_title': {
      AppLanguage.en: 'Medicine Reminders',
      AppLanguage.tr: 'İlaç Hatırlatıcıları',
      AppLanguage.de: 'Medikamenten-Erinnerungen',
      AppLanguage.es: 'Recordatorios de Medicamentos',
      AppLanguage.ar: 'تذكيرات الأدوية',
    },
    'onboarding_medicine_desc': {
      AppLanguage.en: 'Track medications, supplements, and treatments. Get timely reminders for every dose.',
      AppLanguage.tr: 'İlaçları, takviyeleri ve tedavileri takip edin. Her doz için zamanında hatırlatıcı alın.',
      AppLanguage.de: 'Verfolgen Sie Medikamente und Behandlungen. Erhalten Sie rechtzeitige Erinnerungen.',
      AppLanguage.es: 'Rastrea medicamentos y tratamientos. Recibe recordatorios oportunos.',
      AppLanguage.ar: 'تتبع الأدوية والعلاجات. احصل على تذكيرات في الوقت المناسب.',
    },
    'onboarding_vet_title': {
      AppLanguage.en: 'Vet Appointments',
      AppLanguage.tr: 'Veteriner Randevuları',
      AppLanguage.de: 'Tierarzttermine',
      AppLanguage.es: 'Citas Veterinarias',
      AppLanguage.ar: 'مواعيد الطبيب البيطري',
    },
    'onboarding_vet_desc': {
      AppLanguage.en: 'Schedule and track vet visits. Keep all your cat\'s health appointments in one place.',
      AppLanguage.tr: 'Veteriner ziyaretlerini planlayın ve takip edin. Tüm sağlık randevularını tek yerde tutun.',
      AppLanguage.de: 'Planen Sie Tierarztbesuche. Behalten Sie alle Termine an einem Ort.',
      AppLanguage.es: 'Programa visitas al veterinario. Mantén todas las citas en un solo lugar.',
      AppLanguage.ar: 'جدولة زيارات الطبيب البيطري. احتفظ بجميع المواعيد في مكان واحد.',
    },
    'onboarding_food_title': {
      AppLanguage.en: 'Feeding Schedule',
      AppLanguage.tr: 'Beslenme Programı',
      AppLanguage.de: 'Fütterungsplan',
      AppLanguage.es: 'Horario de Alimentación',
      AppLanguage.ar: 'جدول التغذية',
    },
    'onboarding_food_desc': {
      AppLanguage.en: 'Set feeding reminders for meals, treats, and supplements. Keep your cat well-fed on schedule.',
      AppLanguage.tr: 'Yemekler, ödüller ve takviyeler için beslenme hatırlatıcıları ayarlayın.',
      AppLanguage.de: 'Richten Sie Fütterungserinnerungen ein. Halten Sie Ihre Katze nach Plan gefüttert.',
      AppLanguage.es: 'Configura recordatorios de alimentación. Mantén a tu gato bien alimentado.',
      AppLanguage.ar: 'قم بإعداد تذكيرات التغذية. حافظ على تغذية قطتك في الموعد.',
    },
    'onboarding_page1_desc': {
      AppLanguage.en: 'dotcat Complete Daily Supply ürününü her gün kullanmanızı hatırlatırken kedinizin tüm bakım takibini yapar.',
      AppLanguage.tr: 'dotcat Complete Daily Supply ürününü her gün kullanmanızı hatırlatırken kedinizin tüm bakım takibini yapar.',
      AppLanguage.de: 'Erinnert Sie täglich an dotcat Complete Daily Supply und verfolgt die gesamte Pflege Ihrer Katze.',
      AppLanguage.es: 'Te recuerda usar dotcat Complete Daily Supply diariamente mientras rastrea todo el cuidado de tu gato.',
      AppLanguage.ar: 'يذكرك باستخدام dotcat Complete Daily Supply يومياً بينما يتتبع جميع رعاية قطتك.',
    },
    'onboarding_page2_title': {
      AppLanguage.en: 'Everything You Need',
      AppLanguage.tr: 'İhtiyacınız Olan Her Şey',
      AppLanguage.de: 'Alles was Sie brauchen',
      AppLanguage.es: 'Todo lo que Necesitas',
      AppLanguage.ar: 'كل ما تحتاجه',
    },
    'onboarding_feature_dotcat': {
      AppLanguage.en: 'Daily dotcat reminder',
      AppLanguage.tr: 'Günlük dotcat hatırlatıcısı',
      AppLanguage.de: 'Tägliche dotcat-Erinnerung',
      AppLanguage.es: 'Recordatorio diario de dotcat',
      AppLanguage.ar: 'تذكير dotcat اليومي',
    },
    'onboarding_feature_weight': {
      AppLanguage.en: 'Weight tracking',
      AppLanguage.tr: 'Kilo takibi',
      AppLanguage.de: 'Gewichtsverfolgung',
      AppLanguage.es: 'Seguimiento de peso',
      AppLanguage.ar: 'تتبع الوزن',
    },
    'onboarding_page3_title': {
      AppLanguage.en: 'Safe & Synced',
      AppLanguage.tr: 'Güvenli & Senkronize',
      AppLanguage.de: 'Sicher & Synchronisiert',
      AppLanguage.es: 'Seguro y Sincronizado',
      AppLanguage.ar: 'آمن ومتزامن',
    },
    'onboarding_page3_desc': {
      AppLanguage.en: 'Sign in to backup your data and access it from any device.',
      AppLanguage.tr: 'Verilerinizi yedeklemek ve herhangi bir cihazdan erişmek için giriş yapın.',
      AppLanguage.de: 'Melden Sie sich an, um Ihre Daten zu sichern.',
      AppLanguage.es: 'Inicia sesión para respaldar tus datos.',
      AppLanguage.ar: 'سجل الدخول لنسخ بياناتك احتياطياً.',
    },
    'login_tagline': {
      AppLanguage.en: 'Track your cat\'s health, never miss a reminder',
      AppLanguage.tr: 'Kedinizin sağlığını takip edin, hiçbir hatırlatmayı kaçırmayın',
      AppLanguage.de: 'Verfolgen Sie die Gesundheit Ihrer Katze',
      AppLanguage.es: 'Rastrea la salud de tu gato',
      AppLanguage.ar: 'تتبع صحة قطتك',
    },
    'sign_in_google': {
      AppLanguage.en: 'Sign in with Google',
      AppLanguage.tr: 'Google ile giriş yap',
      AppLanguage.de: 'Mit Google anmelden',
      AppLanguage.es: 'Iniciar sesión con Google',
      AppLanguage.ar: 'تسجيل الدخول مع جوجل',
    },
    'or': {
      AppLanguage.en: 'or',
      AppLanguage.tr: 'veya',
      AppLanguage.de: 'oder',
      AppLanguage.es: 'o',
      AppLanguage.ar: 'أو',
    },
    'sign_in_anonymous': {
      AppLanguage.en: 'Continue anonymously',
      AppLanguage.tr: 'Anonim olarak devam et',
      AppLanguage.de: 'Anonym fortfahren',
      AppLanguage.es: 'Continuar de forma anónima',
      AppLanguage.ar: 'المتابعة بشكل مجهول',
    },
    'sign_in_email': {
      AppLanguage.en: 'Sign in with Email',
      AppLanguage.tr: 'E-posta ile giriş yap',
      AppLanguage.de: 'Mit E-Mail anmelden',
      AppLanguage.es: 'Iniciar sesión con correo',
      AppLanguage.ar: 'تسجيل الدخول بالبريد الإلكتروني',
    },
    'sign_in_apple': {
      AppLanguage.en: 'Sign in with Apple',
      AppLanguage.tr: 'Apple ile giriş yap',
      AppLanguage.de: 'Mit Apple anmelden',
      AppLanguage.es: 'Iniciar sesión con Apple',
      AppLanguage.ar: 'تسجيل الدخول مع أبل',
    },
    'email': {
      AppLanguage.en: 'Email',
      AppLanguage.tr: 'E-posta',
      AppLanguage.de: 'E-Mail',
      AppLanguage.es: 'Correo',
      AppLanguage.ar: 'البريد الإلكتروني',
    },
    'password': {
      AppLanguage.en: 'Password',
      AppLanguage.tr: 'Şifre',
      AppLanguage.de: 'Passwort',
      AppLanguage.es: 'Contraseña',
      AppLanguage.ar: 'كلمة المرور',
    },
    'sign_up': {
      AppLanguage.en: 'Sign up',
      AppLanguage.tr: 'Kayıt ol',
      AppLanguage.de: 'Registrieren',
      AppLanguage.es: 'Registrarse',
      AppLanguage.ar: 'التسجيل',
    },
    'sign_in': {
      AppLanguage.en: 'Sign in',
      AppLanguage.tr: 'Giriş yap',
      AppLanguage.de: 'Anmelden',
      AppLanguage.es: 'Iniciar sesión',
      AppLanguage.ar: 'تسجيل الدخول',
    },
    'user_not_found': {
      AppLanguage.en: 'User not found. Please sign up first.',
      AppLanguage.tr: 'Kullanıcı bulunamadı. Lütfen önce kayıt olun.',
      AppLanguage.de: 'Benutzer nicht gefunden. Bitte registrieren Sie sich zuerst.',
      AppLanguage.es: 'Usuario no encontrado. Por favor regístrese primero.',
      AppLanguage.ar: 'المستخدم غير موجود. يرجى التسجيل أولاً.',
    },
    'wrong_password': {
      AppLanguage.en: 'Wrong password. Please try again.',
      AppLanguage.tr: 'Yanlış şifre. Lütfen tekrar deneyin.',
      AppLanguage.de: 'Falsches Passwort. Bitte versuchen Sie es erneut.',
      AppLanguage.es: 'Contraseña incorrecta. Por favor intente de nuevo.',
      AppLanguage.ar: 'كلمة مرور خاطئة. يرجى المحاولة مرة أخرى.',
    },
    'email_already_in_use': {
      AppLanguage.en: 'Email is already in use. Please sign in instead.',
      AppLanguage.tr: 'Bu e-posta zaten kullanılıyor. Lütfen giriş yapın.',
      AppLanguage.de: 'E-Mail wird bereits verwendet. Bitte melden Sie sich stattdessen an.',
      AppLanguage.es: 'El correo ya está en uso. Por favor inicie sesión.',
      AppLanguage.ar: 'البريد الإلكتروني مستخدم بالفعل. يرجى تسجيل الدخول بدلاً من ذلك.',
    },
    'weak_password': {
      AppLanguage.en: 'Password is too weak. Please use at least 6 characters.',
      AppLanguage.tr: 'Şifre çok zayıf. Lütfen en az 6 karakter kullanın.',
      AppLanguage.de: 'Passwort ist zu schwach. Bitte verwenden Sie mindestens 6 Zeichen.',
      AppLanguage.es: 'La contraseña es demasiado débil. Por favor use al menos 6 caracteres.',
      AppLanguage.ar: 'كلمة المرور ضعيفة جداً. يرجى استخدام 6 أحرف على الأقل.',
    },
    'invalid_email': {
      AppLanguage.en: 'Invalid email address.',
      AppLanguage.tr: 'Geçersiz e-posta adresi.',
      AppLanguage.de: 'Ungültige E-Mail-Adresse.',
      AppLanguage.es: 'Dirección de correo no válida.',
      AppLanguage.ar: 'عنوان بريد إلكتروني غير صالح.',
    },
    'required': {
      AppLanguage.en: 'is required',
      AppLanguage.tr: 'gerekli',
      AppLanguage.de: 'ist erforderlich',
      AppLanguage.es: 'es requerido',
      AppLanguage.ar: 'مطلوب',
    },
    'already_have_account': {
      AppLanguage.en: 'Already have an account?',
      AppLanguage.tr: 'Zaten hesabınız var mı?',
      AppLanguage.de: 'Haben Sie bereits ein Konto?',
      AppLanguage.es: '¿Ya tienes una cuenta?',
      AppLanguage.ar: 'هل لديك حساب بالفعل؟',
    },
    'dont_have_account': {
      AppLanguage.en: "Don't have an account?",
      AppLanguage.tr: 'Hesabınız yok mu?',
      AppLanguage.de: 'Haben Sie kein Konto?',
      AppLanguage.es: '¿No tienes una cuenta?',
      AppLanguage.ar: 'ليس لديك حساب؟',
    },
    'login_privacy_note': {
      AppLanguage.en: 'Your data stays on your device when using as guest',
      AppLanguage.tr: 'Misafir olarak kullandığınızda verileriniz cihazınızda kalır',
      AppLanguage.de: 'Ihre Daten bleiben auf Ihrem Gerät',
      AppLanguage.es: 'Tus datos permanecen en tu dispositivo',
      AppLanguage.ar: 'تبقى بياناتك على جهازك',
    },
    'skip': {
      AppLanguage.en: 'Skip',
      AppLanguage.tr: 'Atla',
      AppLanguage.de: 'Überspringen',
      AppLanguage.es: 'Omitir',
      AppLanguage.ar: 'تخطي',
    },
    'get_started': {
      AppLanguage.en: 'Get Started',
      AppLanguage.tr: 'Başla',
      AppLanguage.de: 'Loslegen',
      AppLanguage.es: 'Empezar',
      AppLanguage.ar: 'ابدأ',
    },
    'swipe_continue': {
      AppLanguage.en: 'Swipe to continue',
      AppLanguage.tr: 'Devam etmek için kaydır',
      AppLanguage.de: 'Wischen zum Fortfahren',
      AppLanguage.es: 'Desliza para continuar',
      AppLanguage.ar: 'اسحب للمتابعة',
    },
    'onboarding_welcome_title': {
      AppLanguage.en: 'Welcome to PetCare',
      AppLanguage.tr: 'PetCare\'e Hoş Geldiniz',
      AppLanguage.de: 'Willkommen bei PetCare',
      AppLanguage.es: 'Bienvenido a PetCare',
      AppLanguage.ar: 'مرحباً بك في PetCare',
    },
    'onboarding_welcome_desc': {
      AppLanguage.en: 'Your complete companion for cat care. Track health, set reminders, and keep your feline friend happy.',
      AppLanguage.tr: 'Kedi bakımı için eksiksiz yardımcınız. Sağlığı takip edin, hatırlatıcılar ayarlayın.',
      AppLanguage.de: 'Ihr kompletter Begleiter für die Katzenpflege.',
      AppLanguage.es: 'Tu compañero completo para el cuidado de gatos.',
      AppLanguage.ar: 'رفيقك الكامل لرعاية القطط.',
    },
    'onboarding_reminders_title': {
      AppLanguage.en: 'Smart Reminders',
      AppLanguage.tr: 'Akıllı Hatırlatıcılar',
      AppLanguage.de: 'Intelligente Erinnerungen',
      AppLanguage.es: 'Recordatorios Inteligentes',
      AppLanguage.ar: 'تذكيرات ذكية',
    },
    'onboarding_reminders_desc': {
      AppLanguage.en: 'Never miss an important date. Get notified for vaccines, medications, and vet appointments.',
      AppLanguage.tr: 'Önemli tarihleri asla kaçırmayın. Aşılar, ilaçlar ve veteriner randevuları için bildirim alın.',
      AppLanguage.de: 'Verpassen Sie nie ein wichtiges Datum.',
      AppLanguage.es: 'Nunca pierdas una fecha importante.',
      AppLanguage.ar: 'لا تفوت أي موعد مهم.',
    },
    'onboarding_health_title': {
      AppLanguage.en: 'Health Tracking',
      AppLanguage.tr: 'Sağlık Takibi',
      AppLanguage.de: 'Gesundheitsüberwachung',
      AppLanguage.es: 'Seguimiento de Salud',
      AppLanguage.ar: 'تتبع الصحة',
    },
    'onboarding_health_desc': {
      AppLanguage.en: 'Keep a complete health history. Track vaccinations, medications, and vet visits in one place.',
      AppLanguage.tr: 'Tam bir sağlık geçmişi tutun. Aşıları, ilaçları ve veteriner ziyaretlerini tek yerde takip edin.',
      AppLanguage.de: 'Führen Sie eine vollständige Gesundheitsgeschichte.',
      AppLanguage.es: 'Mantén un historial de salud completo.',
      AppLanguage.ar: 'احتفظ بسجل صحي كامل.',
    },
    'onboarding_weight_title': {
      AppLanguage.en: 'Weight Monitoring',
      AppLanguage.tr: 'Kilo Takibi',
      AppLanguage.de: 'Gewichtsüberwachung',
      AppLanguage.es: 'Monitoreo de Peso',
      AppLanguage.ar: 'مراقبة الوزن',
    },
    'onboarding_weight_desc': {
      AppLanguage.en: 'Monitor your cat\'s weight over time with beautiful charts and trends.',
      AppLanguage.tr: 'Güzel grafikler ve trendlerle kedinizin kilosunu zaman içinde izleyin.',
      AppLanguage.de: 'Überwachen Sie das Gewicht Ihrer Katze mit Diagrammen.',
      AppLanguage.es: 'Monitorea el peso de tu gato con gráficos.',
      AppLanguage.ar: 'راقب وزن قطتك بالرسوم البيانية.',
    },
    'onboarding_sync_title': {
      AppLanguage.en: 'Cloud Backup',
      AppLanguage.tr: 'Bulut Yedekleme',
      AppLanguage.de: 'Cloud-Sicherung',
      AppLanguage.es: 'Respaldo en la Nube',
      AppLanguage.ar: 'النسخ الاحتياطي السحابي',
    },
    'onboarding_sync_desc': {
      AppLanguage.en: 'Sign in to backup your data and access it from any device.',
      AppLanguage.tr: 'Verilerinizi yedeklemek ve herhangi bir cihazdan erişmek için giriş yapın.',
      AppLanguage.de: 'Melden Sie sich an, um Ihre Daten zu sichern.',
      AppLanguage.es: 'Inicia sesión para respaldar tus datos.',
      AppLanguage.ar: 'سجل الدخول لنسخ بياناتك احتياطياً.',
    },
    'onboarding_feature_vaccine': {
      AppLanguage.en: 'Vaccine reminders',
      AppLanguage.tr: 'Aşı hatırlatıcıları',
      AppLanguage.de: 'Impferinnerungen',
      AppLanguage.es: 'Recordatorios de vacunas',
      AppLanguage.ar: 'تذكيرات اللقاحات',
    },
    'onboarding_feature_medicine': {
      AppLanguage.en: 'Medication schedules',
      AppLanguage.tr: 'İlaç programları',
      AppLanguage.de: 'Medikamentenpläne',
      AppLanguage.es: 'Horarios de medicación',
      AppLanguage.ar: 'جداول الأدوية',
    },
    'onboarding_feature_vet': {
      AppLanguage.en: 'Vet appointment alerts',
      AppLanguage.tr: 'Veteriner randevu uyarıları',
      AppLanguage.de: 'Tierarzttermin-Benachrichtigungen',
      AppLanguage.es: 'Alertas de citas veterinarias',
      AppLanguage.ar: 'تنبيهات مواعيد الطبيب البيطري',
    },
    'no_overdue_in_range': {
      AppLanguage.en: 'No overdue events in this range',
      AppLanguage.tr: 'Bu aralıkta süresi geçmiş etkinlik yok',
      AppLanguage.de: 'Keine überfälligen Ereignisse in diesem Bereich',
      AppLanguage.es: 'No hay eventos atrasados en este rango',
      AppLanguage.ar: 'لا توجد أحداث متأخرة في هذا النطاق',
    },
    'products': {
      AppLanguage.en: 'Products',
      AppLanguage.tr: 'Ürünleri',
      AppLanguage.de: 'Produkte',
      AppLanguage.es: 'Productos',
      AppLanguage.ar: 'المنتجات',
    },
    'sync_data_from_cloud': {
      AppLanguage.en: 'Sync data from cloud',
      AppLanguage.tr: 'Verileri buluttan senkronize et',
      AppLanguage.de: 'Daten aus der Cloud synchronisieren',
      AppLanguage.es: 'Sincronizar datos desde la nube',
      AppLanguage.ar: 'مزامنة البيانات من السحابة',
    },
    'calendar': {
      AppLanguage.en: 'Calendar',
      AppLanguage.tr: 'Takvim',
      AppLanguage.de: 'Kalender',
      AppLanguage.es: 'Calendario',
      AppLanguage.ar: 'التقويم',
    },
    'login_subtitle': {
      AppLanguage.en: 'Sign in to sync your data across devices',
      AppLanguage.tr: 'Verilerinizi cihazlar arası senkronize edin',
      AppLanguage.de: 'Melden Sie sich an, um Ihre Daten zu synchronisieren',
      AppLanguage.es: 'Inicia sesión para sincronizar tus datos',
      AppLanguage.ar: 'سجل الدخول لمزامنة بياناتك',
    },
    'continue_with_google': {
      AppLanguage.en: 'Continue with Google',
      AppLanguage.tr: 'Google ile devam et',
      AppLanguage.de: 'Mit Google fortfahren',
      AppLanguage.es: 'Continuar con Google',
      AppLanguage.ar: 'المتابعة مع جوجل',
    },
    'continue_without_login': {
      AppLanguage.en: 'Continue without signing in',
      AppLanguage.tr: 'Giriş yapmadan devam et',
      AppLanguage.de: 'Ohne Anmeldung fortfahren',
      AppLanguage.es: 'Continuar sin iniciar sesión',
      AppLanguage.ar: 'المتابعة بدون تسجيل الدخول',
    },
    'login_info': {
      AppLanguage.en: 'Sign in to backup your data and access from other devices.',
      AppLanguage.tr: 'Verilerinizi yedeklemek ve diğer cihazlardan erişmek için giriş yapın.',
      AppLanguage.de: 'Melden Sie sich an, um Ihre Daten zu sichern.',
      AppLanguage.es: 'Inicia sesión para respaldar tus datos.',
      AppLanguage.ar: 'سجل الدخول للنسخ الاحتياطي.',
    },
    'login_cancelled': {
      AppLanguage.en: 'Login cancelled',
      AppLanguage.tr: 'Giriş iptal edildi',
      AppLanguage.de: 'Anmeldung abgebrochen',
      AppLanguage.es: 'Inicio de sesión cancelado',
      AppLanguage.ar: 'تم إلغاء تسجيل الدخول',
    },
    'login_error': {
      AppLanguage.en: 'Login failed. Please try again.',
      AppLanguage.tr: 'Giriş başarısız. Lütfen tekrar deneyin.',
      AppLanguage.de: 'Anmeldung fehlgeschlagen.',
      AppLanguage.es: 'Error de inicio de sesión.',
      AppLanguage.ar: 'فشل تسجيل الدخول.',
    },
    'account': {
      AppLanguage.en: 'Account',
      AppLanguage.tr: 'Hesap',
      AppLanguage.de: 'Konto',
      AppLanguage.es: 'Cuenta',
      AppLanguage.ar: 'الحساب',
    },
    'not_signed_in': {
      AppLanguage.en: 'Not signed in',
      AppLanguage.tr: 'Giriş yapılmadı',
      AppLanguage.de: 'Nicht angemeldet',
      AppLanguage.es: 'No has iniciado sesión',
      AppLanguage.ar: 'لم يتم تسجيل الدخول',
    },
    'sign_in': {
      AppLanguage.en: 'Sign In',
      AppLanguage.tr: 'Giriş Yap',
      AppLanguage.de: 'Anmelden',
      AppLanguage.es: 'Iniciar Sesión',
      AppLanguage.ar: 'تسجيل الدخول',
    },
    'sign_in_to_sync': {
      AppLanguage.en: 'Sign in to sync your data',
      AppLanguage.tr: 'Verilerinizi senkronize etmek için giriş yapın',
      AppLanguage.de: 'Anmelden um Daten zu synchronisieren',
      AppLanguage.es: 'Inicia sesión para sincronizar',
      AppLanguage.ar: 'سجل الدخول للمزامنة',
    },
    'sign_out': {
      AppLanguage.en: 'Sign Out',
      AppLanguage.tr: 'Çıkış Yap',
      AppLanguage.de: 'Abmelden',
      AppLanguage.es: 'Cerrar Sesión',
      AppLanguage.ar: 'تسجيل الخروج',
    },
    'sync_now': {
      AppLanguage.en: 'Sync Now',
      AppLanguage.tr: 'Şimdi Senkronize Et',
      AppLanguage.de: 'Jetzt synchronisieren',
      AppLanguage.es: 'Sincronizar Ahora',
      AppLanguage.ar: 'مزامنة الآن',
    },
    'sync_success': {
      AppLanguage.en: 'Data synced successfully',
      AppLanguage.tr: 'Veriler başarıyla senkronize edildi',
      AppLanguage.de: 'Daten erfolgreich synchronisiert',
      AppLanguage.es: 'Datos sincronizados',
      AppLanguage.ar: 'تمت مزامنة البيانات',
    },
    'sync_error': {
      AppLanguage.en: 'Sync failed. Please try again.',
      AppLanguage.tr: 'Senkronizasyon başarısız. Tekrar deneyin.',
      AppLanguage.de: 'Synchronisierung fehlgeschlagen.',
      AppLanguage.es: 'Error de sincronización.',
      AppLanguage.ar: 'فشلت المزامنة.',
    },
    'past_record': {
      AppLanguage.en: 'Past Record',
      AppLanguage.tr: 'Geçmiş Kayıt',
      AppLanguage.de: 'Vergangener Eintrag',
      AppLanguage.es: 'Registro Pasado',
      AppLanguage.ar: 'سجل سابق',
    },
    'optional_notes': {
      AppLanguage.en: 'Optional notes...',
      AppLanguage.tr: 'İsteğe bağlı notlar...',
      AppLanguage.de: 'Optionale Notizen...',
      AppLanguage.es: 'Notas opcionales...',
      AppLanguage.ar: 'ملاحظات اختيارية...',
    },
    'overdue_events_count': {
      AppLanguage.en: 'overdue',
      AppLanguage.tr: 'gecikmiş',
      AppLanguage.de: 'überfällig',
      AppLanguage.es: 'atrasado',
      AppLanguage.ar: 'متأخر',
    },
    'pending_events_count': {
      AppLanguage.en: 'upcoming',
      AppLanguage.tr: 'yaklaşan',
      AppLanguage.de: 'anstehend',
      AppLanguage.es: 'próximo',
      AppLanguage.ar: 'قادم',
    },
  };

  static String get(String key) {
    return _translations[key]?[currentLanguage] ?? key;
  }

  static void setLanguage(AppLanguage language) {
    currentLanguage = language;
  }

  // Localized age text
  static String getAgeText(int months) {
    if (months < 1) {
      return currentLanguage == AppLanguage.tr ? 'Yeni doğan' : 
             currentLanguage == AppLanguage.de ? 'Neugeboren' : 
             currentLanguage == AppLanguage.es ? 'Recién nacido' : 
             currentLanguage == AppLanguage.ar ? 'حديث الولادة' : 'Newborn';
    } else if (months < 12) {
      return currentLanguage == AppLanguage.tr ? '$months aylık' : 
             currentLanguage == AppLanguage.de ? '$months Monate alt' : 
             currentLanguage == AppLanguage.es ? '$months meses' : 
             currentLanguage == AppLanguage.ar ? '$months أشهر' : '$months months old';
    } else {
      final years = months ~/ 12;
      final remainingMonths = months % 12;
      if (remainingMonths == 0) {
        return currentLanguage == AppLanguage.tr ? '$years yaşında' : 
               currentLanguage == AppLanguage.de ? '$years Jahre alt' : 
               currentLanguage == AppLanguage.es ? '$years años' : 
               currentLanguage == AppLanguage.ar ? '$years سنة' : '$years years old';
      }
      return currentLanguage == AppLanguage.tr ? '$years yıl $remainingMonths ay' : 
             currentLanguage == AppLanguage.de ? '$years J. $remainingMonths M.' : 
             currentLanguage == AppLanguage.es ? '$years a. $remainingMonths m.' : 
             currentLanguage == AppLanguage.ar ? '$years سنة $remainingMonths شهر' : '$years yr $remainingMonths mo';
    }
  }

  // Localized date format
  static String formatLocalizedDate(DateTime date) {
    final months = {
      AppLanguage.tr: ['Oca', 'Şub', 'Mar', 'Nis', 'May', 'Haz', 'Tem', 'Ağu', 'Eyl', 'Eki', 'Kas', 'Ara'],
      AppLanguage.en: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
      AppLanguage.de: ['Jan', 'Feb', 'Mär', 'Apr', 'Mai', 'Jun', 'Jul', 'Aug', 'Sep', 'Okt', 'Nov', 'Dez'],
      AppLanguage.es: ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic'],
      AppLanguage.ar: ['يناير', 'فبراير', 'مارس', 'أبريل', 'مايو', 'يونيو', 'يوليو', 'أغسطس', 'سبتمبر', 'أكتوبر', 'نوفمبر', 'ديسمبر'],
    };
    final monthNames = months[currentLanguage] ?? months[AppLanguage.en]!;
    return '${date.day} ${monthNames[date.month - 1]}';
  }
}
